#!/bin/bash

DMG_DIR="$HOME/Devicelab"
DART="/Volumes/DevicelabCore/dart-sdk/bin/dart"
PUB="/Volumes/DevicelabCore/dart-sdk/bin/pub"

if [[ ! -d "/Volumes/DevicelabCore" && -e "$DMG_DIR/DevicelabCore.dmg" ]]; then
  hdiutil attach "$DMG_DIR/DevicelabCore.dmg"
fi
if [[ ! -d "/Volumes/DevicelabIOS" && -e "$DMG_DIR/DevicelabIOS.dmg" ]]; then
  hdiutil attach "$DMG_DIR/DevicelabIOS.dmg"
fi
if [[ ! -d "/Volumes/DevicelabAndroid" && -e "$DMG_DIR/DevicelabAndroid.dmg" ]]; then
  hdiutil attach "$DMG_DIR/DevicelabAndroid.dmg"
fi

# Update the launch script for next time.
if [[ ! -e "$HOME/start_agent" ]]; then
  cp -f "/Volumes/DevicelabCore/start_agent" "$HOME/start_agent"
fi

# Perform any platform-specific setup.
if [[ -e "/Volumes/DevicelabAndroid/start_agent_additions.sh" ]]; then
  source "/Volumes/DevicelabAndroid/start_agent_additions.sh"
fi
if [[ -e "/Volumes/DevicelabIOS/start_agent_additions.sh" ]]; then
  source "/Volumes/DevicelabIOS/start_agent_additions.sh"
fi

# Copy cocoon to a writable location.
rm -rf "$HOME/cocoon"
cp -r "/Volumes/DevicelabCore/cocoon" "$HOME"

# Fetch dependencies, then start the agent.
cd "$HOME/cocoon/agent"
"$PUB" get
"$DART" bin/agent.dart --config-file "$HOME/config.yaml" ci
