name: cocoon_server
description: server-side functionality shared between `app_dart` and `auto_submit`.
publish_to: none

environment:
  sdk: ^3.7.0

# Version constraints in this package are intentionally relaxed, because the
# exact versions are locked by app_dart and auto_submit apps.
dependencies:
  _discoveryapis_commons: any
  cocoon_common:
    path: ../cocoon_common
  github: ^9.24.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  gql: ^1.0.1-alpha+1709845491443
  graphql: ^5.2.0-beta.9
  http: ^1.2.2
  json_annotation: ^4.8.1
  logging: ^1.2.0
  meta: ^1.16.0
  retry: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.13
  cocoon_server_test:
    path: ../cocoon_server_test
  dart_flutter_team_lints: 3.5.0
  fake_async: ^1.3.2
  json_serializable: ^6.7.1
  mockito: ^5.4.5
  test: ^1.25.8

builders:
  json_serializable: ^3.3.0
