name: cloud
description: Dart gRPC client for Google Cloud APIs

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  async: '>=1.13.3 <3.0.0'
  grpc: ^0.6.6
  protobuf: ^0.10.1

dev_dependencies:
  test: ^1.3.0
