container:
  image: cirrusci/flutter:latest

task:
  name: $CWD
  env:
    matrix:
      - CWD: app
      - CWD: app_dart
      - CWD: agent
  install_tuneup_script: pub global activate tuneup
  pub_script: cd $CWD && pub get
  build_analyze_script: ./build_and_analyze.sh $CWD
  test_script: ./test.sh $CWD
  
task:
  name: app_flutter
  upgrade_script:
  - flutter channel dev
  - flutter upgrade
  pub_script: cd app_flutter && flutter packages get
  build_script: cd app_flutter && flutter config --enable-web && flutter build web && rm lib/generated_plugin_registrant.dart
  analyze_script: cd app_flutter && flutter analyze
  test_script: cd app_flutter && flutter test
