container:
  image: cirrusci/flutter:v1.9.1-hotfix.6

task:
  name: $CWD
  env:
    matrix:
      - CWD: app
      - CWD: app_dart
      - CWD: agent
  install_tuneup_script: pub global activate tuneup
  pub_script: cd $CWD && pub get
  format_script: cd $CWD && dartfmt -n --set-exit-if-changed .
  build_analyze_script: ./build_and_analyze.sh $CWD
  test_script: ./test.sh $CWD

task:
  name: app_flutter
  upgrade_script:
  - flutter channel dev
  - flutter upgrade
  pub_script: cd app_flutter && flutter packages get
  analyze_script: cd app_flutter && flutter analyze
  format_script: cd app_flutter && flutter format --set-exit-if-changed lib/ test/
  build_script: cd app_flutter && flutter config --enable-web && flutter build web
  test_script:
    - cd app_flutter
    - flutter test --test-randomize-ordering-seed=random
    # - flutter test --platform=chrome test/service/appengine_cocoon_test.dart # https://github.com/flutter/flutter/issues/44373
