# Specify analysis options for all of flutter/cocoon
#
# For a list of lints, see: http://dart-lang.github.io/linter/lints/.
# For guidelines on configuring static analysis, see: https://dart.dev/tools/analysis.
include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  errors:
    # TODO(matanlurey): Ignore for now, we have a lot of pre-existing violations.
    avoid_dynamic_calls: ignore
    argument_type_not_assignable: ignore
    comment_references: ignore
    inference_failure_on_collection_literal: ignore
    inference_failure_on_function_invocation: ignore
    inference_failure_on_function_return_type: ignore
    inference_failure_on_instance_creation: ignore
    inference_failure_on_untyped_parameter: ignore
    invalid_assignment: ignore
    lines_longer_than_80_chars: ignore
    only_throw_errors: ignore
    return_of_invalid_type: ignore
  exclude:
    - ".dart_tool/**"
    - "**/*.g.dart"
    - "**/*.pb.dart"
    - "**/*.pbjson.dart"
    - "**/*.pbgrpc.dart"
    - "**/*.pbserver.dart"
    - "**/*.pbenum.dart"
    - "lib/generated_plugin_registrant.dart"
    - "test/**/mocks.mocks.dart"
