# Specify analysis options for all of flutter/cocoon
#
# For a list of lints, see: http://dart-lang.github.io/linter/lints/.
# For guidelines on configuring static analysis, see: https://dart.dev/tools/analysis.
#
# https://github.com/dart-lang/ecosystem/blob/main/pkgs/dart_flutter_team_lints/lib/analysis_options.yaml
include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  errors:
    # TODO(matanlurey): Ignore for now, we have a lot of pre-existing violations.
    avoid_dynamic_calls: ignore
    comment_references: ignore
    deprecated_member_use_from_same_package: ignore
    lines_longer_than_80_chars: ignore
    only_throw_errors: ignore
  exclude:
    - ".dart_tool/**"
    - "**/*.pb.dart"
    - "**/*.pbjson.dart"
    - "**/*.pbgrpc.dart"
    - "**/*.pbserver.dart"
    - "**/*.pbenum.dart"
    - "lib/generated_plugin_registrant.dart"
    - "test/**/mocks.mocks.dart"

# Additional rules that do not *conflict* (i.e. are additive) with dart_flutter_team_lints.
linter:
  rules:
    # - avoid_private_typedef_functions
    # - avoid_unused_constructor_parameters
    prefer_final_locals: true
