steps:

- id: Initialize git
  name: gcr.io/cloud-builders/git
  entrypoint: /bin/bash
  args:
  - -exc
  - |
    git clone 'https://github.com/flutter/flutter.git' tmp
    export PATH="$PATH:tmp/flutter/bin"
    flutter --version
    git clone 'https://github.com/flutter/cocoon.git' tmp

