steps:

- name: gcr.io/tvolkert-test/flutter
  entrypoint: '/bin/bash'
  args: ['cloud_build/app_flutter_build.sh']

- name: gcr.io/tvolkert-test/flutter
  entrypoint: '/bin/bash'
  args: ['cloud_build/app_build.sh']

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: '/bin/bash'
  args: ['cloud_build/deploy.sh']