steps:

- name: gcr.io/cloud-builders/git
  entrypoint: /bin/bash
  args:
  - -exc
  - |
    git clone 'https://github.com/flutter/flutter.git' tmp

- name: gcr.io/cloud-builders/gcloud
  args: ['app', 'deploy', '--project', 'tvolkert-test', '--version', 'testkeyonghan', '--no-promote', '--no-stop-previous-version']


  