steps:

- id: Initialize git
  name: gcr.io/cloud-builders/git
  entrypoint: /bin/bash
  args:
  - -exc
  - |
    sudo apt-get install unzip
    git clone 'https://github.com/flutter/flutter.git' tmp
    tmp/bin/flutter --version

