steps:

#- name: gcr.io/cloud-builders/git
#  entrypoint: /bin/bash
#  args:
#  - -exc
#  - |
#    git clone 'https://github.com/flutter/flutter.git' tmp



#- name: 'gcr.io/cloud-builders/git'
#  args: ['clone', 'https://github.com/flutter/cocoon']
#  dir: '/workspace'

- name: gcr.io/tvolkert-test/flutter
  entrypoint: '/bin/bash'
  args: ['build.sh']

- name: 'gcr.io/cloud-builders/gcloud'
entrypoint: '/bin/bash'
args: ['build2.sh']