// Copyright 2019 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCenA4U4l5CNiLJZDca2zlS0TrX8H7bV9s',
    appId: '1:790958376406:web:abd3f6e0f2d7e77a439077',
    messagingSenderId: '790958376406',
    projectId: 'google.com:flutter-roll-on-borg',
    authDomain: 'com-flutter-roll-on-borg.firebaseapp.com',
    measurementId: 'G-L1088K9MZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfqDitDE3wWJCezm9PfkKBgaLjJrA4H-0',
    appId: '1:790958376406:android:abb9b428ae957864439077',
    messagingSenderId: '790958376406',
    projectId: 'google.com:flutter-roll-on-borg',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOGTpCjagNvzVxgfsxMmISMN0Wgk2Wb7o',
    appId: '1:790958376406:ios:d4e9c944f0a2af41439077',
    messagingSenderId: '790958376406',
    projectId: 'google.com:flutter-roll-on-borg',
    iosBundleId: 'com.example.appFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOGTpCjagNvzVxgfsxMmISMN0Wgk2Wb7o',
    appId: '1:790958376406:ios:d4e9c944f0a2af41439077',
    messagingSenderId: '790958376406',
    projectId: 'google.com:flutter-roll-on-borg',
    iosBundleId: 'com.example.appFlutter',
  );
}
