# Copyright 2022 The Flutter Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Use Google's official Dart image.
# https://hub.docker.com/r/google/dart-runtime/
FROM google/dart-runtime:dev:@sha256:401b118e8fe9b791129d156f0918c740d441e94a395c8b37167315a4318ace6f

# ONBUILD instructions for COPY and pub get is defined in the google/dart-runtime image,
# allowing you to keep this file very simple, see:
# https://github.com/dart-lang/dart_docker/blob/master/runtime/Dockerfile.template#L15-L18
