name: cocoon_server_test
description: Testing specific functionality for package:cocoon_server
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  cocoon_server:
    path: ../cocoon_server
  github: ^9.24.0
  googleapis: ^13.2.0
  http: ^1.3.0
  matcher: ^0.12.17
  mockito: ^5.4.5

dev_dependencies:
  build_runner: ^2.4.15
  dart_flutter_team_lints: ^3.4.0
  test: ^1.25.15
