# Copyright 2019 The Flutter Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

runtime: custom
env: flex
service: releases

resources:
  memory_gb: 2.0

readiness_check:
  path: "/readiness_check"
  check_interval_sec: 20
  timeout_sec: 20
  failure_threshold: 10
  success_threshold: 2
  app_start_timeout_sec: 300
