name: cocoon_scheduler
description: Flutter infrastructure scheduler
repository: https://github.com/flutter/cocoon/tree/master/scheduler
version: 1.0.0

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  protobuf: ^1.0.0
  yaml: ^2.1.16

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
