// Copyright 2022 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

String webhookEventMock = '''{
  "action": "opened",
  "number": 2,
  "pull_request": {
    "url": "https://api.github.com/repos/flutter/cocoon/pulls/2",
    "id": 294034,
    "node_id": "MDExOlB1bGxSZXF1ZXN0Mjk0MDMzODQx",
    "html_url": "https://github.com/flutter/cocoon/pull/2",
    "diff_url": "https://github.com/flutter/cocoon/pull/2.diff",
    "patch_url": "https://github.com/flutter/cocoon/pull/2.patch",
    "issue_url": "https://api.github.com/repos/flutter/cocoon/issues/2",
    "number": 2,
    "state": "open",
    "locked": false,
    "title": "Defer reassemble until reload is finished",
    "user": {
      "login": "flutter",
      "id": 862741,
      "node_id": "MDQ6VXNlcjg2MjA3NDE=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/8620741?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/flutter",
      "html_url": "https://github.com/flutter",
      "followers_url": "https://api.github.com/users/flutter/followers",
      "following_url": "https://api.github.com/users/flutter/following{/other_user}",
      "gists_url": "https://api.github.com/users/flutter/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/flutter/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/flutter/subscriptions",
      "organizations_url": "https://api.github.com/users/flutter/orgs",
      "repos_url": "https://api.github.com/users/flutter/repos",
      "events_url": "https://api.github.com/users/flutter/events{/privacy}",
      "received_events_url": "https://api.github.com/users/flutter/received_events",
      "type": "User",
      "site_admin": false
    },
    "draft" : "false",
    "body": "The body",
    "created_at": "2019-07-03T07:14:35Z",
    "updated_at": "2019-07-03T16:34:53Z",
    "closed_at": null,
    "merged_at": "2019-07-03T16:34:53Z",
    "merge_commit_sha": "d22ab7ced21d3b2a5be00cf576d383eb5ffddb8a",
    "assignee": null,
    "assignees": [],
    "requested_reviewers": [],
    "requested_teams": [],
    "labels": [
      {
        "id": 487496476,
        "node_id": "MDU6TGFiZWw0ODc0OTY0NzY=",
        "url": "https://api.github.com/repos/flutter/cocoon/labels/cla:%20yes",
        "name": "cla: yes",
        "color": "ffffff",
        "default": false
      },
      {
        "id": 284437560,
        "node_id": "MDU6TGFiZWwyODQ0Mzc1NjA=",
        "url": "https://api.github.com/repos/flutter/cocoon/labels/framework",
        "name": "autosubmit",
        "color": "207de5",
        "default": false
      }
    ],
    "milestone": null,
    "commits_url": "https://api.github.com/repos/flutter/cocoon/pulls/2/commits",
    "review_comments_url": "https://api.github.com/repos/flutter/cocoon/pulls/2/comments",
    "review_comment_url": "https://api.github.com/repos/flutter/cocoon/pulls/comments{/number}",
    "comments_url": "https://api.github.com/repos/flutter/cocoon/issues/2/comments",
    "statuses_url": "https://api.github.com/repos/flutter/cocoon/statuses/be6ff099a4ee56e152a5fa2f37edd10f79d1269a",
    "head": {
      "label": "cocoon:changes",
      "ref": "changes",
      "sha": "be6ff099a4ee56e152a5fa2f37edd10f79d1269a",
      "user": {
        "login": "cocoon",
        "id": 8620741,
        "node_id": "MDQ6VXNlcjg2MjA3NDE=",
        "avatar_url": "https://avatars3.githubusercontent.com/u/8620741?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/flutter",
        "html_url": "https://github.com/flutter",
        "followers_url": "https://api.github.com/users/flutter/followers",
        "following_url": "https://api.github.com/users/flutter/following{/other_user}",
        "gists_url": "https://api.github.com/users/flutter/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/flutter/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/flutter/subscriptions",
        "organizations_url": "https://api.github.com/users/flutter/orgs",
        "repos_url": "https://api.github.com/users/flutter/repos",
        "events_url": "https://api.github.com/users/flutter/events{/privacy}",
        "received_events_url": "https://api.github.com/users/flutter/received_events",
        "type": "User",
        "site_admin": false
      },
      "repo": {
        "id": 131232406,
        "node_id": "MDEwOlJlcG9zaXRvcnkxMzEyMzI0MDY=",
        "name": "cocoon",
        "full_name": "flutter/cocoon",
        "private": false,
        "owner": {
          "login": "flutter",
          "id": 8620741,
          "node_id": "MDQ6VXNlcjg2MjA3NDE=",
          "avatar_url": "https://avatars3.githubusercontent.com/u/8620741?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/flutter",
          "html_url": "https://github.com/flutter",
          "followers_url": "https://api.github.com/users/flutter/followers",
          "following_url": "https://api.github.com/users/flutter/following{/other_user}",
          "gists_url": "https://api.github.com/users/flutter/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/flutter/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/flutter/subscriptions",
          "organizations_url": "https://api.github.com/users/flutter/orgs",
          "repos_url": "https://api.github.com/users/flutter/repos",
          "events_url": "https://api.github.com/users/flutter/events{/privacy}",
          "received_events_url": "https://api.github.com/users/flutter/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/flutter/cocoon",
        "description": "Flutter makes it easy and fast to build beautiful mobile apps.",
        "fork": true,
        "url": "https://api.github.com/repos/flutter/cocoon",
        "forks_url": "https://api.github.com/repos/flutter/cocoon/forks",
        "keys_url": "https://api.github.com/repos/flutter/cocoon/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/flutter/cocoon/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/flutter/cocoon/teams",
        "hooks_url": "https://api.github.com/repos/flutter/cocoon/hooks",
        "issue_events_url": "https://api.github.com/repos/flutter/cocoon/issues/events{/number}",
        "events_url": "https://api.github.com/repos/flutter/cocoon/events",
        "assignees_url": "https://api.github.com/repos/flutter/cocoon/assignees{/user}",
        "branches_url": "https://api.github.com/repos/flutter/cocoon/branches{/branch}",
        "tags_url": "https://api.github.com/repos/flutter/cocoon/tags",
        "blobs_url": "https://api.github.com/repos/flutter/cocoon/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/flutter/cocoon/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/flutter/cocoon/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/flutter/cocoon/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/flutter/cocoon/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/flutter/cocoon/languages",
        "stargazers_url": "https://api.github.com/repos/flutter/cocoon/stargazers",
        "contributors_url": "https://api.github.com/repos/flutter/cocoon/contributors",
        "subscribers_url": "https://api.github.com/repos/flutter/cocoon/subscribers",
        "subscription_url": "https://api.github.com/repos/flutter/cocoon/subscription",
        "commits_url": "https://api.github.com/repos/flutter/cocoon/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/flutter/cocoon/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/flutter/cocoon/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/flutter/cocoon/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/flutter/cocoon/contents/{+path}",
        "compare_url": "https://api.github.com/repos/flutter/cocoon/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/flutter/cocoon/merges",
        "archive_url": "https://api.github.com/repos/flutter/cocoon/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/flutter/cocoon/downloads",
        "issues_url": "https://api.github.com/repos/flutter/cocoon/issues{/number}",
        "pulls_url": "https://api.github.com/repos/flutter/cocoon/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/flutter/cocoon/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/flutter/cocoon/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/flutter/cocoon/labels{/name}",
        "releases_url": "https://api.github.com/repos/flutter/cocoon/releases{/id}",
        "deployments_url": "https://api.github.com/repos/flutter/cocoon/deployments",
        "created_at": "2018-04-27T02:03:08Z",
        "updated_at": "2019-06-27T06:56:59Z",
        "pushed_at": "2019-07-03T19:40:11Z",
        "git_url": "git://github.com/flutter/cocoon.git",
        "ssh_url": "git@github.com:flutter/cocoon.git",
        "clone_url": "https://github.com/flutter/cocoon.git",
        "svn_url": "https://github.com/flutter/cocoon",
        "homepage": "https://flutter.io",
        "size": 94508,
        "stargazers_count": 1,
        "watchers_count": 1,
        "language": "Dart",
        "has_issues": false,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": {
          "key": "other",
          "name": "Other",
          "spdx_id": "NOASSERTION",
          "url": null,
          "node_id": "MDc6TGljZW5zZTA="
        },
        "forks": 0,
        "open_issues": 0,
        "watchers": 1,
        "default_branch": "main"
      }
    },
    "base": {
      "label": "flutter:master",
      "ref": "master",
      "sha": "4cd12fc8b7d4cc2d8609182e1c4dea5cddc86890",
      "user": {
        "login": "flutter",
        "id": 14101776,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjE0MTAxNzc2",
        "avatar_url": "https://avatars3.githubblahblahblah",
        "gravatar_id": "",
        "url": "https://api.github.com/users/flutter",
        "html_url": "https://github.com/flutter",
        "followers_url": "https://api.github.com/users/flutter/followers",
        "following_url": "https://api.github.com/users/flutter/following{/other_user}",
        "gists_url": "https://api.github.com/users/flutter/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/flutter/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/flutter/subscriptions",
        "organizations_url": "https://api.github.com/users/flutter/orgs",
        "repos_url": "https://api.github.com/users/flutter/repos",
        "events_url": "https://api.github.com/users/flutter/events{/privacy}",
        "received_events_url": "https://api.github.com/users/flutter/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "repo": {
        "id": 31792824,
        "node_id": "MDEwOlJlcG9zaXRvcnkzMTc5MjgyNA==",
        "name": "cocoon",
        "full_name": "flutter/cocoon",
        "private": false,
        "owner": {
          "login": "flutter",
          "id": 14101776,
          "node_id": "MDEyOk9yZ2FuaXphdGlvbjE0MTAxNzc2",
          "avatar_url": "https://avatars3.githubblahblahblah",
          "gravatar_id": "",
          "url": "https://api.github.com/users/flutter",
          "html_url": "https://github.com/flutter",
          "followers_url": "https://api.github.com/users/flutter/followers",
          "following_url": "https://api.github.com/users/flutter/following{/other_user}",
          "gists_url": "https://api.github.com/users/flutter/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/flutter/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/flutter/subscriptions",
          "organizations_url": "https://api.github.com/users/flutter/orgs",
          "repos_url": "https://api.github.com/users/flutter/repos",
          "events_url": "https://api.github.com/users/flutter/events{/privacy}",
          "received_events_url": "https://api.github.com/users/flutter/received_events",
          "type": "Organization",
          "site_admin": false
        },
        "html_url": "https://github.com/flutter/cocoon",
        "description": "Flutter makes it easy and fast to build beautiful mobile apps.",
        "fork": false,
        "url": "https://api.github.com/repos/flutter/cocoon",
        "forks_url": "https://api.github.com/repos/flutter/cocoon/forks",
        "keys_url": "https://api.github.com/repos/flutter/cocoon/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/flutter/cocoon/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/flutter/cocoon/teams",
        "hooks_url": "https://api.github.com/repos/flutter/cocoon/hooks",
        "issue_events_url": "https://api.github.com/repos/flutter/cocoon/issues/events{/number}",
        "events_url": "https://api.github.com/repos/flutter/cocoon/events",
        "assignees_url": "https://api.github.com/repos/flutter/cocoon/assignees{/user}",
        "branches_url": "https://api.github.com/repos/flutter/cocoon/branches{/branch}",
        "tags_url": "https://api.github.com/repos/flutter/cocoon/tags",
        "blobs_url": "https://api.github.com/repos/flutter/cocoon/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/flutter/cocoon/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/flutter/cocoon/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/flutter/cocoon/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/flutter/cocoon/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/flutter/cocoon/languages",
        "stargazers_url": "https://api.github.com/repos/flutter/cocoon/stargazers",
        "contributors_url": "https://api.github.com/repos/flutter/cocoon/contributors",
        "subscribers_url": "https://api.github.com/repos/flutter/cocoon/subscribers",
        "subscription_url": "https://api.github.com/repos/flutter/cocoon/subscription",
        "commits_url": "https://api.github.com/repos/flutter/cocoon/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/flutter/cocoon/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/flutter/cocoon/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/flutter/cocoon/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/flutter/cocoon/contents/{+path}",
        "compare_url": "https://api.github.com/repos/flutter/cocoon/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/flutter/cocoon/merges",
        "archive_url": "https://api.github.com/repos/flutter/cocoon/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/flutter/cocoon/downloads",
        "issues_url": "https://api.github.com/repos/flutter/cocoon/issues{/number}",
        "pulls_url": "https://api.github.com/repos/flutter/cocoon/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/flutter/cocoon/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/flutter/cocoon/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/flutter/cocoon/labels{/name}",
        "releases_url": "https://api.github.com/repos/flutter/cocoon/releases{/id}",
        "deployments_url": "https://api.github.com/repos/flutter/cocoon/deployments",
        "created_at": "2015-03-06T22:54:58Z",
        "updated_at": "2019-07-04T02:08:44Z",
        "pushed_at": "2019-07-04T02:03:04Z",
        "git_url": "git://github.com/flutter/cocoon.git",
        "ssh_url": "git@github.com:flutter/cocoon.git",
        "clone_url": "https://github.com/flutter/cocoon.git",
        "svn_url": "https://github.com/flutter/cocoon",
        "homepage": "https://flutter.dev",
        "size": 65507,
        "stargazers_count": 68944,
        "watchers_count": 68944,
        "language": "Dart",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 7987,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 6536,
        "license": {
          "key": "other",
          "name": "Other",
          "spdx_id": "NOASSERTION",
          "url": null,
          "node_id": "MDc6TGljZW5zZTA="
        },
        "forks": 7987,
        "open_issues": 6536,
        "watchers": 68944,
        "default_branch": "main"
      }
    },
    "_links": {
      "self": {
        "href": "https://api.github.com/repos/flutter/cocoon/pulls/2"
      },
      "html": {
        "href": "https://github.com/flutter/cocoon/pull/2"
      },
      "issue": {
        "href": "https://api.github.com/repos/flutter/cocoon/issues/2"
      },
      "comments": {
        "href": "https://api.github.com/repos/flutter/cocoon/issues/2/comments"
      },
      "review_comments": {
        "href": "https://api.github.com/repos/flutter/cocoon/pulls/2/comments"
      },
      "review_comment": {
        "href": "https://api.github.com/repos/flutter/cocoon/pulls/comments{/number}"
      },
      "commits": {
        "href": "https://api.github.com/repos/flutter/cocoon/pulls/2/commits"
      },
      "statuses": {
        "href": "https://api.github.com/repos/flutter/cocoon/statuses/deadbeef"
      }
    },
    "author_association": "MEMBER",
    "draft" : false,
    "merged": false,
    "mergeable": null,
    "rebaseable": true,
    "mergeable_state": "draft",
    "merged_by": null,
    "comments": 1,
    "review_comments": 0,
    "maintainer_can_modify": true,
    "commits": 5,
    "additions": 55,
    "deletions": 36,
    "changed_files": 5
  },
  "repository": {
    "id": 1868532,
    "node_id": "MDEwOlJlcG9zaXRvcnkxODY4NTMwMDI=",
    "name": "cocoon",
    "full_name": "flutter/cocoon",
    "private": false,
    "owner": {
      "login": "flutter",
      "id": 21031067,
      "node_id": "MDQ6VXNlcjIxMDMxMDY3",
      "avatar_url": "https://avatars1.githubusercontent.com/u/21031067?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/flutter",
      "html_url": "https://github.com/flutter",
      "followers_url": "https://api.github.com/users/flutter/followers",
      "following_url": "https://api.github.com/users/flutter/following{/other_user}",
      "gists_url": "https://api.github.com/users/flutter/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/flutter/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/flutter/subscriptions",
      "organizations_url": "https://api.github.com/users/flutter/orgs",
      "repos_url": "https://api.github.com/users/flutter/repos",
      "events_url": "https://api.github.com/users/flutter/events{/privacy}",
      "received_events_url": "https://api.github.com/users/flutter/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/flutter/cocoon",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/flutter/cocoon",
    "forks_url": "https://api.github.com/repos/flutter/cocoon/forks",
    "keys_url": "https://api.github.com/repos/flutter/cocoon/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/flutter/cocoon/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/flutter/cocoon/teams",
    "hooks_url": "https://api.github.com/repos/flutter/cocoon/hooks",
    "issue_events_url": "https://api.github.com/repos/flutter/cocoon/issues/events{/number}",
    "events_url": "https://api.github.com/repos/flutter/cocoon/events",
    "assignees_url": "https://api.github.com/repos/flutter/cocoon/assignees{/user}",
    "branches_url": "https://api.github.com/repos/flutter/cocoon/branches{/branch}",
    "tags_url": "https://api.github.com/repos/flutter/cocoon/tags",
    "blobs_url": "https://api.github.com/repos/flutter/cocoon/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/flutter/cocoon/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/flutter/cocoon/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/flutter/cocoon/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/flutter/cocoon/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/flutter/cocoon/languages",
    "stargazers_url": "https://api.github.com/repos/flutter/cocoon/stargazers",
    "contributors_url": "https://api.github.com/repos/flutter/cocoon/contributors",
    "subscribers_url": "https://api.github.com/repos/flutter/cocoon/subscribers",
    "subscription_url": "https://api.github.com/repos/flutter/cocoon/subscription",
    "commits_url": "https://api.github.com/repos/flutter/cocoon/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/flutter/cocoon/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/flutter/cocoon/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/flutter/cocoon/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/flutter/cocoon/contents/{+path}",
    "compare_url": "https://api.github.com/repos/flutter/cocoon/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/flutter/cocoon/merges",
    "archive_url": "https://api.github.com/repos/flutter/cocoon/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/flutter/cocoon/downloads",
    "issues_url": "https://api.github.com/repos/flutter/cocoon/issues{/number}",
    "pulls_url": "https://api.github.com/repos/flutter/cocoon/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/flutter/cocoon/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/flutter/cocoon/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/flutter/cocoon/labels{/name}",
    "releases_url": "https://api.github.com/repos/flutter/cocoon/releases{/id}",
    "deployments_url": "https://api.github.com/repos/flutter/cocoon/deployments",
    "created_at": "2019-05-15T15:19:25Z",
    "updated_at": "2019-05-15T15:19:27Z",
    "pushed_at": "2019-05-15T15:20:32Z",
    "git_url": "git://github.com/flutter/cocoon.git",
    "ssh_url": "git@github.com:flutter/cocoon.git",
    "clone_url": "https://github.com/flutter/cocoon.git",
    "svn_url": "https://github.com/flutter/cocoon",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 2,
    "license": null,
    "forks": 0,
    "open_issues": 2,
    "watchers": 0,
    "default_branch": "master"
  },
  "sender": {
    "login": "cocoon",
    "id": 21031067,
    "node_id": "MDQ6VXNlcjIxMDMxMDY3",
    "avatar_url": "https://avatars1.githubusercontent.com/u/21031067?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/flutter",
    "html_url": "https://github.com/flutter",
    "followers_url": "https://api.github.com/users/flutter/followers",
    "following_url": "https://api.github.com/users/flutter/following{/other_user}",
    "gists_url": "https://api.github.com/users/flutter/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/flutter/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/flutter/subscriptions",
    "organizations_url": "https://api.github.com/users/flutter/orgs",
    "repos_url": "https://api.github.com/users/flutter/repos",
    "events_url": "https://api.github.com/users/flutter/events{/privacy}",
    "received_events_url": "https://api.github.com/users/flutter/received_events",
    "type": "User",
    "site_admin": false
  }
}''';

String singlePullRequestMock = '''{
  "url": "https://api.github.com/repos/flutter/cocoon/pulls/1347",
  "id": 1,
  "node_id": "MDExOlB1bGxSZXF1ZXN0MQ==",
  "html_url": "https://github.com/flutter/cocoon/pull/1347",
  "diff_url": "https://github.com/flutter/cocoon/pull/1347.diff",
  "patch_url": "https://github.com/flutter/cocoon/pull/1347.patch",
  "issue_url": "https://api.github.com/repos/flutter/cocoon/issues/1347",
  "commits_url": "https://api.github.com/repos/flutter/cocoon/pulls/1347/commits",
  "review_comments_url": "https://api.github.com/repos/flutter/cocoon/pulls/1347/comments",
  "review_comment_url": "https://api.github.com/repos/flutter/cocoon/pulls/comments{/number}",
  "comments_url": "https://api.github.com/repos/flutter/cocoon/issues/1347/comments",
  "statuses_url": "https://api.github.com/repos/flutter/cocoon/statuses/6dcb09b5b57875f334f61aebed695e2e4193db5e",
  "number": 1598,
  "state": "open",
  "locked": true,
  "title": "Amazing new feature",
  "user": {
    "login": "flutter",
    "id": 1,
    "node_id": "MDQ6VXNlcjE=",
    "avatar_url": "https://github.com/images/error/flutter_happy.gif",
    "gravatar_id": "",
    "url": "https://api.github.com/users/flutter",
    "html_url": "https://github.com/flutter",
    "followers_url": "https://api.github.com/users/flutter/followers",
    "following_url": "https://api.github.com/users/flutter/following{/other_user}",
    "gists_url": "https://api.github.com/users/flutter/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/flutter/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/flutter/subscriptions",
    "organizations_url": "https://api.github.com/users/flutter/orgs",
    "repos_url": "https://api.github.com/users/flutter/repos",
    "events_url": "https://api.github.com/users/flutter/events{/privacy}",
    "received_events_url": "https://api.github.com/users/flutter/received_events",
    "type": "User",
    "site_admin": false
  },
  "body": "Please pull these awesome changes in!",
  "labels": [
    {
      "id": 208045946,
      "node_id": "MDU6TGFiZWwyMDgwNDU5NDY=",
      "url": "https://api.github.com/repos/flutter/cocoon/labels/bug",
      "name": "bug",
      "description": "Something isn't working",
      "color": "f29513",
      "default": true
    }
  ],
  "milestone": {
    "url": "https://api.github.com/repos/flutter/cocoon/milestones/1",
    "html_url": "https://github.com/flutter/cocoon/milestones/v1.0",
    "labels_url": "https://api.github.com/repos/flutter/cocoon/milestones/1/labels",
    "id": 1002604,
    "node_id": "MDk6TWlsZXN0b25lMTAwMjYwNA==",
    "number": 1,
    "state": "open",
    "title": "v1.0",
    "description": "Tracking milestone for version 1.0",
    "creator": {
      "login": "flutter",
      "id": 1,
      "node_id": "MDQ6VXNlcjE=",
      "avatar_url": "https://github.com/images/error/flutter_happy.gif",
      "gravatar_id": "",
      "url": "https://api.github.com/users/flutter",
      "html_url": "https://github.com/flutter",
      "followers_url": "https://api.github.com/users/flutter/followers",
      "following_url": "https://api.github.com/users/flutter/following{/other_user}",
      "gists_url": "https://api.github.com/users/flutter/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/flutter/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/flutter/subscriptions",
      "organizations_url": "https://api.github.com/users/flutter/orgs",
      "repos_url": "https://api.github.com/users/flutter/repos",
      "events_url": "https://api.github.com/users/flutter/events{/privacy}",
      "received_events_url": "https://api.github.com/users/flutter/received_events",
      "type": "User",
      "site_admin": false
    },
    "open_issues": 4,
    "closed_issues": 8,
    "created_at": "2011-04-10T20:09:31Z",
    "updated_at": "2014-03-03T18:58:10Z",
    "closed_at": "2013-02-12T13:22:01Z",
    "due_on": "2012-10-09T23:39:01Z"
  },
  "active_lock_reason": "too heated",
  "created_at": "2011-01-26T19:01:12Z",
  "updated_at": "2011-01-26T19:01:12Z",
  "closed_at": "2011-01-26T19:01:12Z",
  "merged_at": "2011-01-26T19:01:12Z",
  "merge_commit_sha": "e5bd3914e2e596debea16f433f57875b5b90bcd6",
  "assignee": {
    "login": "flutter",
    "id": 1,
    "node_id": "MDQ6VXNlcjE=",
    "avatar_url": "https://github.com/images/error/flutter_happy.gif",
    "gravatar_id": "",
    "url": "https://api.github.com/users/flutter",
    "html_url": "https://github.com/flutter",
    "followers_url": "https://api.github.com/users/flutter/followers",
    "following_url": "https://api.github.com/users/flutter/following{/other_user}",
    "gists_url": "https://api.github.com/users/flutter/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/flutter/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/flutter/subscriptions",
    "organizations_url": "https://api.github.com/users/flutter/orgs",
    "repos_url": "https://api.github.com/users/flutter/repos",
    "events_url": "https://api.github.com/users/flutter/events{/privacy}",
    "received_events_url": "https://api.github.com/users/flutter/received_events",
    "type": "User",
    "site_admin": false
  },
  "assignees": [
    {
      "login": "flutter",
      "id": 1,
      "node_id": "MDQ6VXNlcjE=",
      "avatar_url": "https://github.com/images/error/flutter_happy.gif",
      "gravatar_id": "",
      "url": "https://api.github.com/users/flutter",
      "html_url": "https://github.com/flutter",
      "followers_url": "https://api.github.com/users/flutter/followers",
      "following_url": "https://api.github.com/users/flutter/following{/other_user}",
      "gists_url": "https://api.github.com/users/flutter/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/flutter/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/flutter/subscriptions",
      "organizations_url": "https://api.github.com/users/flutter/orgs",
      "repos_url": "https://api.github.com/users/flutter/repos",
      "events_url": "https://api.github.com/users/flutter/events{/privacy}",
      "received_events_url": "https://api.github.com/users/flutter/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "hubot",
      "id": 1,
      "node_id": "MDQ6VXNlcjE=",
      "avatar_url": "https://github.com/images/error/hubot_happy.gif",
      "gravatar_id": "",
      "url": "https://api.github.com/users/hubot",
      "html_url": "https://github.com/hubot",
      "followers_url": "https://api.github.com/users/hubot/followers",
      "following_url": "https://api.github.com/users/hubot/following{/other_user}",
      "gists_url": "https://api.github.com/users/hubot/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/hubot/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/hubot/subscriptions",
      "organizations_url": "https://api.github.com/users/hubot/orgs",
      "repos_url": "https://api.github.com/users/hubot/repos",
      "events_url": "https://api.github.com/users/hubot/events{/privacy}",
      "received_events_url": "https://api.github.com/users/hubot/received_events",
      "type": "User",
      "site_admin": true
    }
  ],
  "requested_reviewers": [
    {
      "login": "other_user",
      "id": 1,
      "node_id": "MDQ6VXNlcjE=",
      "avatar_url": "https://github.com/images/error/other_user_happy.gif",
      "gravatar_id": "",
      "url": "https://api.github.com/users/other_user",
      "html_url": "https://github.com/other_user",
      "followers_url": "https://api.github.com/users/other_user/followers",
      "following_url": "https://api.github.com/users/other_user/following{/other_user}",
      "gists_url": "https://api.github.com/users/other_user/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/other_user/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/other_user/subscriptions",
      "organizations_url": "https://api.github.com/users/other_user/orgs",
      "repos_url": "https://api.github.com/users/other_user/repos",
      "events_url": "https://api.github.com/users/other_user/events{/privacy}",
      "received_events_url": "https://api.github.com/users/other_user/received_events",
      "type": "User",
      "site_admin": false
    }
  ],
  "requested_teams": [
    {
      "id": 1,
      "node_id": "MDQ6VGVhbTE=",
      "url": "https://api.github.com/teams/1",
      "html_url": "https://github.com/orgs/github/teams/justice-league",
      "name": "Justice League",
      "slug": "justice-league",
      "description": "A great team.",
      "privacy": "closed",
      "permission": "admin",
      "members_url": "https://api.github.com/teams/1/members{/member}",
      "repositories_url": "https://api.github.com/teams/1/repos"
    }
  ],
  "head": {
    "label": "flutter:new-topic",
    "ref": "new-topic",
    "sha": "be6ff099a4ee56e152a5fa2f37edd10f79d1269a",
    "user": {
      "login": "flutter",
      "id": 1,
      "node_id": "MDQ6VXNlcjE=",
      "avatar_url": "https://github.com/images/error/flutter_happy.gif",
      "gravatar_id": "",
      "url": "https://api.github.com/users/flutter",
      "html_url": "https://github.com/flutter",
      "followers_url": "https://api.github.com/users/flutter/followers",
      "following_url": "https://api.github.com/users/flutter/following{/other_user}",
      "gists_url": "https://api.github.com/users/flutter/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/flutter/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/flutter/subscriptions",
      "organizations_url": "https://api.github.com/users/flutter/orgs",
      "repos_url": "https://api.github.com/users/flutter/repos",
      "events_url": "https://api.github.com/users/flutter/events{/privacy}",
      "received_events_url": "https://api.github.com/users/flutter/received_events",
      "type": "User",
      "site_admin": false
    },
    "repo": {
      "id": 1296269,
      "node_id": "MDEwOlJlcG9zaXRvcnkxMjk2MjY5",
      "name": "cocoon",
      "full_name": "flutter/cocoon",
      "owner": {
        "login": "flutter",
        "id": 1,
        "node_id": "MDQ6VXNlcjE=",
        "avatar_url": "https://github.com/images/error/flutter_happy.gif",
        "gravatar_id": "",
        "url": "https://api.github.com/users/flutter",
        "html_url": "https://github.com/flutter",
        "followers_url": "https://api.github.com/users/flutter/followers",
        "following_url": "https://api.github.com/users/flutter/following{/other_user}",
        "gists_url": "https://api.github.com/users/flutter/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/flutter/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/flutter/subscriptions",
        "organizations_url": "https://api.github.com/users/flutter/orgs",
        "repos_url": "https://api.github.com/users/flutter/repos",
        "events_url": "https://api.github.com/users/flutter/events{/privacy}",
        "received_events_url": "https://api.github.com/users/flutter/received_events",
        "type": "User",
        "site_admin": false
      },
      "private": false,
      "html_url": "https://github.com/flutter/cocoon",
      "description": "This your first repo!",
      "fork": false,
      "url": "https://api.github.com/repos/flutter/cocoon",
      "archive_url": "https://api.github.com/repos/flutter/cocoon/{archive_format}{/ref}",
      "assignees_url": "https://api.github.com/repos/flutter/cocoon/assignees{/user}",
      "blobs_url": "https://api.github.com/repos/flutter/cocoon/git/blobs{/sha}",
      "branches_url": "https://api.github.com/repos/flutter/cocoon/branches{/branch}",
      "collaborators_url": "https://api.github.com/repos/flutter/cocoon/collaborators{/collaborator}",
      "comments_url": "https://api.github.com/repos/flutter/cocoon/comments{/number}",
      "commits_url": "https://api.github.com/repos/flutter/cocoon/commits{/sha}",
      "compare_url": "https://api.github.com/repos/flutter/cocoon/compare/{base}...{head}",
      "contents_url": "https://api.github.com/repos/flutter/cocoon/contents/{+path}",
      "contributors_url": "https://api.github.com/repos/flutter/cocoon/contributors",
      "deployments_url": "https://api.github.com/repos/flutter/cocoon/deployments",
      "downloads_url": "https://api.github.com/repos/flutter/cocoon/downloads",
      "events_url": "https://api.github.com/repos/flutter/cocoon/events",
      "forks_url": "https://api.github.com/repos/flutter/cocoon/forks",
      "git_commits_url": "https://api.github.com/repos/flutter/cocoon/git/commits{/sha}",
      "git_refs_url": "https://api.github.com/repos/flutter/cocoon/git/refs{/sha}",
      "git_tags_url": "https://api.github.com/repos/flutter/cocoon/git/tags{/sha}",
      "git_url": "git:github.com/flutter/cocoon.git",
      "issue_comment_url": "https://api.github.com/repos/flutter/cocoon/issues/comments{/number}",
      "issue_events_url": "https://api.github.com/repos/flutter/cocoon/issues/events{/number}",
      "issues_url": "https://api.github.com/repos/flutter/cocoon/issues{/number}",
      "keys_url": "https://api.github.com/repos/flutter/cocoon/keys{/key_id}",
      "labels_url": "https://api.github.com/repos/flutter/cocoon/labels{/name}",
      "languages_url": "https://api.github.com/repos/flutter/cocoon/languages",
      "merges_url": "https://api.github.com/repos/flutter/cocoon/merges",
      "milestones_url": "https://api.github.com/repos/flutter/cocoon/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/flutter/cocoon/notifications{?since,all,participating}",
      "pulls_url": "https://api.github.com/repos/flutter/cocoon/pulls{/number}",
      "releases_url": "https://api.github.com/repos/flutter/cocoon/releases{/id}",
      "ssh_url": "git@github.com:flutter/cocoon.git",
      "stargazers_url": "https://api.github.com/repos/flutter/cocoon/stargazers",
      "statuses_url": "https://api.github.com/repos/flutter/cocoon/statuses/{sha}",
      "subscribers_url": "https://api.github.com/repos/flutter/cocoon/subscribers",
      "subscription_url": "https://api.github.com/repos/flutter/cocoon/subscription",
      "tags_url": "https://api.github.com/repos/flutter/cocoon/tags",
      "teams_url": "https://api.github.com/repos/flutter/cocoon/teams",
      "trees_url": "https://api.github.com/repos/flutter/cocoon/git/trees{/sha}",
      "clone_url": "https://github.com/flutter/cocoon.git",
      "mirror_url": "git:git.example.com/flutter/cocoon",
      "hooks_url": "https://api.github.com/repos/flutter/cocoon/hooks",
      "svn_url": "https://svn.github.com/flutter/cocoon",
      "homepage": "https://github.com",
      "language": null,
      "forks_count": 9,
      "stargazers_count": 80,
      "watchers_count": 80,
      "size": 108,
      "default_branch": "master",
      "open_issues_count": 0,
      "topics": [
        "flutter",
        "atom",
        "electron",
        "api"
      ],
      "has_issues": true,
      "has_projects": true,
      "has_wiki": true,
      "has_pages": false,
      "has_downloads": true,
      "archived": false,
      "disabled": false,
      "pushed_at": "2011-01-26T19:06:43Z",
      "created_at": "2011-01-26T19:01:12Z",
      "updated_at": "2011-01-26T19:14:43Z",
      "permissions": {
        "admin": false,
        "push": false,
        "pull": true
      },
      "allow_rebase_merge": true,
      "temp_clone_token": "ABTLWHOULUVAXGTRYU7OC2876QJ2O",
      "allow_squash_merge": true,
      "allow_merge_commit": true,
      "allow_forking": true,
      "forks": 123,
      "open_issues": 123,
      "license": {
        "key": "mit",
        "name": "MIT License",
        "url": "https://api.github.com/licenses/mit",
        "spdx_id": "MIT",
        "node_id": "MDc6TGljZW5zZW1pdA=="
      },
      "watchers": 123
    }
  },
  "base": {
    "label": "flutter:master",
    "ref": "master",
    "sha": "6dcb09b5b57875f334f61aebed695e2e4193db5e",
    "user": {
      "login": "flutter",
      "id": 1,
      "node_id": "MDQ6VXNlcjE=",
      "avatar_url": "https://github.com/images/error/flutter_happy.gif",
      "gravatar_id": "",
      "url": "https://api.github.com/users/flutter",
      "html_url": "https://github.com/flutter",
      "followers_url": "https://api.github.com/users/flutter/followers",
      "following_url": "https://api.github.com/users/flutter/following{/other_user}",
      "gists_url": "https://api.github.com/users/flutter/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/flutter/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/flutter/subscriptions",
      "organizations_url": "https://api.github.com/users/flutter/orgs",
      "repos_url": "https://api.github.com/users/flutter/repos",
      "events_url": "https://api.github.com/users/flutter/events{/privacy}",
      "received_events_url": "https://api.github.com/users/flutter/received_events",
      "type": "User",
      "site_admin": false
    },
    "repo": {
      "id": 1296269,
      "node_id": "MDEwOlJlcG9zaXRvcnkxMjk2MjY5",
      "name": "cocoon",
      "full_name": "flutter/cocoon",
      "owner": {
        "login": "flutter",
        "id": 1,
        "node_id": "MDQ6VXNlcjE=",
        "avatar_url": "https://github.com/images/error/flutter_happy.gif",
        "gravatar_id": "",
        "url": "https://api.github.com/users/flutter",
        "html_url": "https://github.com/flutter",
        "followers_url": "https://api.github.com/users/flutter/followers",
        "following_url": "https://api.github.com/users/flutter/following{/other_user}",
        "gists_url": "https://api.github.com/users/flutter/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/flutter/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/flutter/subscriptions",
        "organizations_url": "https://api.github.com/users/flutter/orgs",
        "repos_url": "https://api.github.com/users/flutter/repos",
        "events_url": "https://api.github.com/users/flutter/events{/privacy}",
        "received_events_url": "https://api.github.com/users/flutter/received_events",
        "type": "User",
        "site_admin": false
      },
      "private": false,
      "html_url": "https://github.com/flutter/cocoon",
      "description": "This your first repo!",
      "fork": false,
      "url": "https://api.github.com/repos/flutter/cocoon",
      "archive_url": "https://api.github.com/repos/flutter/cocoon/{archive_format}{/ref}",
      "assignees_url": "https://api.github.com/repos/flutter/cocoon/assignees{/user}",
      "blobs_url": "https://api.github.com/repos/flutter/cocoon/git/blobs{/sha}",
      "branches_url": "https://api.github.com/repos/flutter/cocoon/branches{/branch}",
      "collaborators_url": "https://api.github.com/repos/flutter/cocoon/collaborators{/collaborator}",
      "comments_url": "https://api.github.com/repos/flutter/cocoon/comments{/number}",
      "commits_url": "https://api.github.com/repos/flutter/cocoon/commits{/sha}",
      "compare_url": "https://api.github.com/repos/flutter/cocoon/compare/{base}...{head}",
      "contents_url": "https://api.github.com/repos/flutter/cocoon/contents/{+path}",
      "contributors_url": "https://api.github.com/repos/flutter/cocoon/contributors",
      "deployments_url": "https://api.github.com/repos/flutter/cocoon/deployments",
      "downloads_url": "https://api.github.com/repos/flutter/cocoon/downloads",
      "events_url": "https://api.github.com/repos/flutter/cocoon/events",
      "forks_url": "https://api.github.com/repos/flutter/cocoon/forks",
      "git_commits_url": "https://api.github.com/repos/flutter/cocoon/git/commits{/sha}",
      "git_refs_url": "https://api.github.com/repos/flutter/cocoon/git/refs{/sha}",
      "git_tags_url": "https://api.github.com/repos/flutter/cocoon/git/tags{/sha}",
      "git_url": "git:github.com/flutter/cocoon.git",
      "issue_comment_url": "https://api.github.com/repos/flutter/cocoon/issues/comments{/number}",
      "issue_events_url": "https://api.github.com/repos/flutter/cocoon/issues/events{/number}",
      "issues_url": "https://api.github.com/repos/flutter/cocoon/issues{/number}",
      "keys_url": "https://api.github.com/repos/flutter/cocoon/keys{/key_id}",
      "labels_url": "https://api.github.com/repos/flutter/cocoon/labels{/name}",
      "languages_url": "https://api.github.com/repos/flutter/cocoon/languages",
      "merges_url": "https://api.github.com/repos/flutter/cocoon/merges",
      "milestones_url": "https://api.github.com/repos/flutter/cocoon/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/flutter/cocoon/notifications{?since,all,participating}",
      "pulls_url": "https://api.github.com/repos/flutter/cocoon/pulls{/number}",
      "releases_url": "https://api.github.com/repos/flutter/cocoon/releases{/id}",
      "ssh_url": "git@github.com:flutter/cocoon.git",
      "stargazers_url": "https://api.github.com/repos/flutter/cocoon/stargazers",
      "statuses_url": "https://api.github.com/repos/flutter/cocoon/statuses/{sha}",
      "subscribers_url": "https://api.github.com/repos/flutter/cocoon/subscribers",
      "subscription_url": "https://api.github.com/repos/flutter/cocoon/subscription",
      "tags_url": "https://api.github.com/repos/flutter/cocoon/tags",
      "teams_url": "https://api.github.com/repos/flutter/cocoon/teams",
      "trees_url": "https://api.github.com/repos/flutter/cocoon/git/trees{/sha}",
      "clone_url": "https://github.com/flutter/cocoon.git",
      "mirror_url": "git:git.example.com/flutter/cocoon",
      "hooks_url": "https://api.github.com/repos/flutter/cocoon/hooks",
      "svn_url": "https://svn.github.com/flutter/cocoon",
      "homepage": "https://github.com",
      "language": null,
      "forks_count": 9,
      "stargazers_count": 80,
      "watchers_count": 80,
      "size": 108,
      "default_branch": "master",
      "open_issues_count": 0,
      "topics": [
        "flutter",
        "atom",
        "electron",
        "api"
      ],
      "has_issues": true,
      "has_projects": true,
      "has_wiki": true,
      "has_pages": false,
      "has_downloads": true,
      "archived": false,
      "disabled": false,
      "pushed_at": "2011-01-26T19:06:43Z",
      "created_at": "2011-01-26T19:01:12Z",
      "updated_at": "2011-01-26T19:14:43Z",
      "permissions": {
        "admin": false,
        "push": false,
        "pull": true
      },
      "allow_rebase_merge": true,
      "temp_clone_token": "ABTLWHOULUVAXGTRYU7OC2876QJ2O",
      "allow_squash_merge": true,
      "allow_merge_commit": true,
      "forks": 123,
      "open_issues": 123,
      "license": {
        "key": "mit",
        "name": "MIT License",
        "url": "https://api.github.com/licenses/mit",
        "spdx_id": "MIT",
        "node_id": "MDc6TGljZW5zZW1pdA=="
      },
      "watchers": 123
    }
  },
  "_links": {
    "self": {
      "href": "https://api.github.com/repos/flutter/cocoon/pulls/1347"
    },
    "html": {
      "href": "https://github.com/flutter/cocoon/pull/1347"
    },
    "issue": {
      "href": "https://api.github.com/repos/flutter/cocoon/issues/1347"
    },
    "comments": {
      "href": "https://api.github.com/repos/flutter/cocoon/issues/1347/comments"
    },
    "review_comments": {
      "href": "https://api.github.com/repos/flutter/cocoon/pulls/1347/comments"
    },
    "review_comment": {
      "href": "https://api.github.com/repos/flutter/cocoon/pulls/comments{/number}"
    },
    "commits": {
      "href": "https://api.github.com/repos/flutter/cocoon/pulls/1347/commits"
    },
    "statuses": {
      "href": "https://api.github.com/repos/flutter/cocoon/statuses/6dcb09b5b57875f334f61aebed695e2e4193db5e"
    }
  },
  "author_association": "OWNER",
  "auto_merge": null,
  "draft": false,
  "merged": false,
  "mergeable": true,
  "rebaseable": true,
  "mergeable_state": "clean",
  "merged_by": {
    "login": "flutter",
    "id": 1,
    "node_id": "MDQ6VXNlcjE=",
    "avatar_url": "https://github.com/images/error/flutter_happy.gif",
    "gravatar_id": "",
    "url": "https://api.github.com/users/flutter",
    "html_url": "https://github.com/flutter",
    "followers_url": "https://api.github.com/users/flutter/followers",
    "following_url": "https://api.github.com/users/flutter/following{/other_user}",
    "gists_url": "https://api.github.com/users/flutter/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/flutter/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/flutter/subscriptions",
    "organizations_url": "https://api.github.com/users/flutter/orgs",
    "repos_url": "https://api.github.com/users/flutter/repos",
    "events_url": "https://api.github.com/users/flutter/events{/privacy}",
    "received_events_url": "https://api.github.com/users/flutter/received_events",
    "type": "User",
    "site_admin": false
  },
  "comments": 10,
  "review_comments": 0,
  "maintainer_can_modify": true,
  "commits": 3,
  "additions": 100,
  "deletions": 3,
  "changed_files": 5
}''';
