targets:
  $default:
    builders:
      json_serializable:
        options:
          generate_to_json_function: false
      build_web_compilers|entrypoint:
        generate_for:
        - web/**.dart
        options:
          dart2js_args:
          - --dump-info
          - --fast-startup
          - --minify
          - --omit-implicit-checks
          - --trust-primitives
          - --no-source-maps