name: cocoon_server
description: server-side functionality shared between `app_dart` and `auto_submit`.
publish_to: none

environment:
  sdk: ^3.1.0

dependencies:
  logging: 1.2.0
  meta: 1.16.0
  retry: 3.1.2
  googleapis: 13.2.0
  googleapis_auth: 1.6.0
  graphql: 5.2.0-beta.9
  gql: 1.0.1-alpha+1709845491443
  http: 1.2.2
  github: 9.24.0

dev_dependencies:
  build_runner: 2.4.13
  fake_async: 1.3.2
  mockito: 5.4.4
  test: 1.25.8
  analyzer: ^6.0.0
  json_serializable: 6.7.1

builders:
  json_serializable: 3.3.0
