// Mocks generated by Mockito 5.4.5 from annotations
// in cocoon_server/test/firestore_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:googleapis/firestore/v1.dart' as _i2;
import 'package:googleapis/shared.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProjectsResource_0 extends _i1.SmartFake
    implements _i2.ProjectsResource {
  _FakeProjectsResource_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProjectsDatabasesResource_1 extends _i1.SmartFake
    implements _i2.ProjectsDatabasesResource {
  _FakeProjectsDatabasesResource_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProjectsLocationsResource_2 extends _i1.SmartFake
    implements _i2.ProjectsLocationsResource {
  _FakeProjectsLocationsResource_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProjectsDatabasesBackupSchedulesResource_3 extends _i1.SmartFake
    implements _i2.ProjectsDatabasesBackupSchedulesResource {
  _FakeProjectsDatabasesBackupSchedulesResource_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeProjectsDatabasesCollectionGroupsResource_4 extends _i1.SmartFake
    implements _i2.ProjectsDatabasesCollectionGroupsResource {
  _FakeProjectsDatabasesCollectionGroupsResource_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeProjectsDatabasesDocumentsResource_5 extends _i1.SmartFake
    implements _i2.ProjectsDatabasesDocumentsResource {
  _FakeProjectsDatabasesDocumentsResource_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeProjectsDatabasesOperationsResource_6 extends _i1.SmartFake
    implements _i2.ProjectsDatabasesOperationsResource {
  _FakeProjectsDatabasesOperationsResource_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeGoogleLongrunningOperation_7 extends _i1.SmartFake
    implements _i2.GoogleLongrunningOperation {
  _FakeGoogleLongrunningOperation_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoogleFirestoreAdminV1Database_8 extends _i1.SmartFake
    implements _i2.GoogleFirestoreAdminV1Database {
  _FakeGoogleFirestoreAdminV1Database_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeGoogleFirestoreAdminV1ListDatabasesResponse_9 extends _i1.SmartFake
    implements _i2.GoogleFirestoreAdminV1ListDatabasesResponse {
  _FakeGoogleFirestoreAdminV1ListDatabasesResponse_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeBatchWriteResponse_10 extends _i1.SmartFake
    implements _i2.BatchWriteResponse {
  _FakeBatchWriteResponse_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBeginTransactionResponse_11 extends _i1.SmartFake
    implements _i2.BeginTransactionResponse {
  _FakeBeginTransactionResponse_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCommitResponse_12 extends _i1.SmartFake
    implements _i2.CommitResponse {
  _FakeCommitResponse_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDocument_13 extends _i1.SmartFake implements _i2.Document {
  _FakeDocument_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$Empty_14 extends _i1.SmartFake implements _i3.$Empty {
  _Fake$Empty_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeListDocumentsResponse_15 extends _i1.SmartFake
    implements _i2.ListDocumentsResponse {
  _FakeListDocumentsResponse_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeListCollectionIdsResponse_16 extends _i1.SmartFake
    implements _i2.ListCollectionIdsResponse {
  _FakeListCollectionIdsResponse_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePartitionQueryResponse_17 extends _i1.SmartFake
    implements _i2.PartitionQueryResponse {
  _FakePartitionQueryResponse_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWriteResponse_18 extends _i1.SmartFake implements _i2.WriteResponse {
  _FakeWriteResponse_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FirestoreApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreApi extends _i1.Mock implements _i2.FirestoreApi {
  @override
  _i2.ProjectsResource get projects =>
      (super.noSuchMethod(
            Invocation.getter(#projects),
            returnValue: _FakeProjectsResource_0(
              this,
              Invocation.getter(#projects),
            ),
            returnValueForMissingStub: _FakeProjectsResource_0(
              this,
              Invocation.getter(#projects),
            ),
          )
          as _i2.ProjectsResource);
}

/// A class which mocks [ProjectsResource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProjectsResource extends _i1.Mock implements _i2.ProjectsResource {
  @override
  _i2.ProjectsDatabasesResource get databases =>
      (super.noSuchMethod(
            Invocation.getter(#databases),
            returnValue: _FakeProjectsDatabasesResource_1(
              this,
              Invocation.getter(#databases),
            ),
            returnValueForMissingStub: _FakeProjectsDatabasesResource_1(
              this,
              Invocation.getter(#databases),
            ),
          )
          as _i2.ProjectsDatabasesResource);

  @override
  _i2.ProjectsLocationsResource get locations =>
      (super.noSuchMethod(
            Invocation.getter(#locations),
            returnValue: _FakeProjectsLocationsResource_2(
              this,
              Invocation.getter(#locations),
            ),
            returnValueForMissingStub: _FakeProjectsLocationsResource_2(
              this,
              Invocation.getter(#locations),
            ),
          )
          as _i2.ProjectsLocationsResource);
}

/// A class which mocks [ProjectsDatabasesResource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProjectsDatabasesResource extends _i1.Mock
    implements _i2.ProjectsDatabasesResource {
  @override
  _i2.ProjectsDatabasesBackupSchedulesResource get backupSchedules =>
      (super.noSuchMethod(
            Invocation.getter(#backupSchedules),
            returnValue: _FakeProjectsDatabasesBackupSchedulesResource_3(
              this,
              Invocation.getter(#backupSchedules),
            ),
            returnValueForMissingStub:
                _FakeProjectsDatabasesBackupSchedulesResource_3(
                  this,
                  Invocation.getter(#backupSchedules),
                ),
          )
          as _i2.ProjectsDatabasesBackupSchedulesResource);

  @override
  _i2.ProjectsDatabasesCollectionGroupsResource get collectionGroups =>
      (super.noSuchMethod(
            Invocation.getter(#collectionGroups),
            returnValue: _FakeProjectsDatabasesCollectionGroupsResource_4(
              this,
              Invocation.getter(#collectionGroups),
            ),
            returnValueForMissingStub:
                _FakeProjectsDatabasesCollectionGroupsResource_4(
                  this,
                  Invocation.getter(#collectionGroups),
                ),
          )
          as _i2.ProjectsDatabasesCollectionGroupsResource);

  @override
  _i2.ProjectsDatabasesDocumentsResource get documents =>
      (super.noSuchMethod(
            Invocation.getter(#documents),
            returnValue: _FakeProjectsDatabasesDocumentsResource_5(
              this,
              Invocation.getter(#documents),
            ),
            returnValueForMissingStub:
                _FakeProjectsDatabasesDocumentsResource_5(
                  this,
                  Invocation.getter(#documents),
                ),
          )
          as _i2.ProjectsDatabasesDocumentsResource);

  @override
  _i2.ProjectsDatabasesOperationsResource get operations =>
      (super.noSuchMethod(
            Invocation.getter(#operations),
            returnValue: _FakeProjectsDatabasesOperationsResource_6(
              this,
              Invocation.getter(#operations),
            ),
            returnValueForMissingStub:
                _FakeProjectsDatabasesOperationsResource_6(
                  this,
                  Invocation.getter(#operations),
                ),
          )
          as _i2.ProjectsDatabasesOperationsResource);

  @override
  _i4.Future<_i2.GoogleLongrunningOperation> create(
    _i2.GoogleFirestoreAdminV1Database? request,
    String? parent, {
    String? databaseId,
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #create,
              [request, parent],
              {#databaseId: databaseId, #$fields: $fields},
            ),
            returnValue: _i4.Future<_i2.GoogleLongrunningOperation>.value(
              _FakeGoogleLongrunningOperation_7(
                this,
                Invocation.method(
                  #create,
                  [request, parent],
                  {#databaseId: databaseId, #$fields: $fields},
                ),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.GoogleLongrunningOperation>.value(
                  _FakeGoogleLongrunningOperation_7(
                    this,
                    Invocation.method(
                      #create,
                      [request, parent],
                      {#databaseId: databaseId, #$fields: $fields},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.GoogleLongrunningOperation>);

  @override
  _i4.Future<_i2.GoogleLongrunningOperation> delete(
    String? name, {
    String? etag,
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [name],
              {#etag: etag, #$fields: $fields},
            ),
            returnValue: _i4.Future<_i2.GoogleLongrunningOperation>.value(
              _FakeGoogleLongrunningOperation_7(
                this,
                Invocation.method(
                  #delete,
                  [name],
                  {#etag: etag, #$fields: $fields},
                ),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.GoogleLongrunningOperation>.value(
                  _FakeGoogleLongrunningOperation_7(
                    this,
                    Invocation.method(
                      #delete,
                      [name],
                      {#etag: etag, #$fields: $fields},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.GoogleLongrunningOperation>);

  @override
  _i4.Future<_i2.GoogleLongrunningOperation> exportDocuments(
    _i2.GoogleFirestoreAdminV1ExportDocumentsRequest? request,
    String? name, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #exportDocuments,
              [request, name],
              {#$fields: $fields},
            ),
            returnValue: _i4.Future<_i2.GoogleLongrunningOperation>.value(
              _FakeGoogleLongrunningOperation_7(
                this,
                Invocation.method(
                  #exportDocuments,
                  [request, name],
                  {#$fields: $fields},
                ),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.GoogleLongrunningOperation>.value(
                  _FakeGoogleLongrunningOperation_7(
                    this,
                    Invocation.method(
                      #exportDocuments,
                      [request, name],
                      {#$fields: $fields},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.GoogleLongrunningOperation>);

  @override
  _i4.Future<_i2.GoogleFirestoreAdminV1Database> get(
    String? name, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#get, [name], {#$fields: $fields}),
            returnValue: _i4.Future<_i2.GoogleFirestoreAdminV1Database>.value(
              _FakeGoogleFirestoreAdminV1Database_8(
                this,
                Invocation.method(#get, [name], {#$fields: $fields}),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.GoogleFirestoreAdminV1Database>.value(
                  _FakeGoogleFirestoreAdminV1Database_8(
                    this,
                    Invocation.method(#get, [name], {#$fields: $fields}),
                  ),
                ),
          )
          as _i4.Future<_i2.GoogleFirestoreAdminV1Database>);

  @override
  _i4.Future<_i2.GoogleLongrunningOperation> importDocuments(
    _i2.GoogleFirestoreAdminV1ImportDocumentsRequest? request,
    String? name, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #importDocuments,
              [request, name],
              {#$fields: $fields},
            ),
            returnValue: _i4.Future<_i2.GoogleLongrunningOperation>.value(
              _FakeGoogleLongrunningOperation_7(
                this,
                Invocation.method(
                  #importDocuments,
                  [request, name],
                  {#$fields: $fields},
                ),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.GoogleLongrunningOperation>.value(
                  _FakeGoogleLongrunningOperation_7(
                    this,
                    Invocation.method(
                      #importDocuments,
                      [request, name],
                      {#$fields: $fields},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.GoogleLongrunningOperation>);

  @override
  _i4.Future<_i2.GoogleFirestoreAdminV1ListDatabasesResponse> list(
    String? parent, {
    bool? showDeleted,
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #list,
              [parent],
              {#showDeleted: showDeleted, #$fields: $fields},
            ),
            returnValue: _i4.Future<
              _i2.GoogleFirestoreAdminV1ListDatabasesResponse
            >.value(
              _FakeGoogleFirestoreAdminV1ListDatabasesResponse_9(
                this,
                Invocation.method(
                  #list,
                  [parent],
                  {#showDeleted: showDeleted, #$fields: $fields},
                ),
              ),
            ),
            returnValueForMissingStub: _i4.Future<
              _i2.GoogleFirestoreAdminV1ListDatabasesResponse
            >.value(
              _FakeGoogleFirestoreAdminV1ListDatabasesResponse_9(
                this,
                Invocation.method(
                  #list,
                  [parent],
                  {#showDeleted: showDeleted, #$fields: $fields},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.GoogleFirestoreAdminV1ListDatabasesResponse>);

  @override
  _i4.Future<_i2.GoogleLongrunningOperation> patch(
    _i2.GoogleFirestoreAdminV1Database? request,
    String? name, {
    String? updateMask,
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [request, name],
              {#updateMask: updateMask, #$fields: $fields},
            ),
            returnValue: _i4.Future<_i2.GoogleLongrunningOperation>.value(
              _FakeGoogleLongrunningOperation_7(
                this,
                Invocation.method(
                  #patch,
                  [request, name],
                  {#updateMask: updateMask, #$fields: $fields},
                ),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.GoogleLongrunningOperation>.value(
                  _FakeGoogleLongrunningOperation_7(
                    this,
                    Invocation.method(
                      #patch,
                      [request, name],
                      {#updateMask: updateMask, #$fields: $fields},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.GoogleLongrunningOperation>);

  @override
  _i4.Future<_i2.GoogleLongrunningOperation> restore(
    _i2.GoogleFirestoreAdminV1RestoreDatabaseRequest? request,
    String? parent, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#restore, [request, parent], {#$fields: $fields}),
            returnValue: _i4.Future<_i2.GoogleLongrunningOperation>.value(
              _FakeGoogleLongrunningOperation_7(
                this,
                Invocation.method(
                  #restore,
                  [request, parent],
                  {#$fields: $fields},
                ),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.GoogleLongrunningOperation>.value(
                  _FakeGoogleLongrunningOperation_7(
                    this,
                    Invocation.method(
                      #restore,
                      [request, parent],
                      {#$fields: $fields},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.GoogleLongrunningOperation>);
}

/// A class which mocks [ProjectsDatabasesDocumentsResource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProjectsDatabasesDocumentsResource extends _i1.Mock
    implements _i2.ProjectsDatabasesDocumentsResource {
  MockProjectsDatabasesDocumentsResource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.BatchGetDocumentsResponseElement>> batchGet(
    _i2.BatchGetDocumentsRequest? request,
    String? database, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #batchGet,
              [request, database],
              {#$fields: $fields},
            ),
            returnValue:
                _i4.Future<List<_i2.BatchGetDocumentsResponseElement>>.value(
                  <_i2.BatchGetDocumentsResponseElement>[],
                ),
          )
          as _i4.Future<List<_i2.BatchGetDocumentsResponseElement>>);

  @override
  _i4.Future<_i2.BatchWriteResponse> batchWrite(
    _i2.BatchWriteRequest? request,
    String? database, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #batchWrite,
              [request, database],
              {#$fields: $fields},
            ),
            returnValue: _i4.Future<_i2.BatchWriteResponse>.value(
              _FakeBatchWriteResponse_10(
                this,
                Invocation.method(
                  #batchWrite,
                  [request, database],
                  {#$fields: $fields},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.BatchWriteResponse>);

  @override
  _i4.Future<_i2.BeginTransactionResponse> beginTransaction(
    _i2.BeginTransactionRequest? request,
    String? database, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #beginTransaction,
              [request, database],
              {#$fields: $fields},
            ),
            returnValue: _i4.Future<_i2.BeginTransactionResponse>.value(
              _FakeBeginTransactionResponse_11(
                this,
                Invocation.method(
                  #beginTransaction,
                  [request, database],
                  {#$fields: $fields},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.BeginTransactionResponse>);

  @override
  _i4.Future<_i2.CommitResponse> commit(
    _i2.CommitRequest? request,
    String? database, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #commit,
              [request, database],
              {#$fields: $fields},
            ),
            returnValue: _i4.Future<_i2.CommitResponse>.value(
              _FakeCommitResponse_12(
                this,
                Invocation.method(
                  #commit,
                  [request, database],
                  {#$fields: $fields},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.CommitResponse>);

  @override
  _i4.Future<_i2.Document> createDocument(
    _i2.Document? request,
    String? parent,
    String? collectionId, {
    String? documentId,
    List<String>? mask_fieldPaths,
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createDocument,
              [request, parent, collectionId],
              {
                #documentId: documentId,
                #mask_fieldPaths: mask_fieldPaths,
                #$fields: $fields,
              },
            ),
            returnValue: _i4.Future<_i2.Document>.value(
              _FakeDocument_13(
                this,
                Invocation.method(
                  #createDocument,
                  [request, parent, collectionId],
                  {
                    #documentId: documentId,
                    #mask_fieldPaths: mask_fieldPaths,
                    #$fields: $fields,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Document>);

  @override
  _i4.Future<_i3.$Empty> delete(
    String? name, {
    bool? currentDocument_exists,
    String? currentDocument_updateTime,
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [name],
              {
                #currentDocument_exists: currentDocument_exists,
                #currentDocument_updateTime: currentDocument_updateTime,
                #$fields: $fields,
              },
            ),
            returnValue: _i4.Future<_i3.$Empty>.value(
              _Fake$Empty_14(
                this,
                Invocation.method(
                  #delete,
                  [name],
                  {
                    #currentDocument_exists: currentDocument_exists,
                    #currentDocument_updateTime: currentDocument_updateTime,
                    #$fields: $fields,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i3.$Empty>);

  @override
  _i4.Future<_i2.Document> get(
    String? name, {
    List<String>? mask_fieldPaths,
    String? readTime,
    String? transaction,
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [name],
              {
                #mask_fieldPaths: mask_fieldPaths,
                #readTime: readTime,
                #transaction: transaction,
                #$fields: $fields,
              },
            ),
            returnValue: _i4.Future<_i2.Document>.value(
              _FakeDocument_13(
                this,
                Invocation.method(
                  #get,
                  [name],
                  {
                    #mask_fieldPaths: mask_fieldPaths,
                    #readTime: readTime,
                    #transaction: transaction,
                    #$fields: $fields,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Document>);

  @override
  _i4.Future<_i2.ListDocumentsResponse> list(
    String? parent,
    String? collectionId, {
    List<String>? mask_fieldPaths,
    String? orderBy,
    int? pageSize,
    String? pageToken,
    String? readTime,
    bool? showMissing,
    String? transaction,
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #list,
              [parent, collectionId],
              {
                #mask_fieldPaths: mask_fieldPaths,
                #orderBy: orderBy,
                #pageSize: pageSize,
                #pageToken: pageToken,
                #readTime: readTime,
                #showMissing: showMissing,
                #transaction: transaction,
                #$fields: $fields,
              },
            ),
            returnValue: _i4.Future<_i2.ListDocumentsResponse>.value(
              _FakeListDocumentsResponse_15(
                this,
                Invocation.method(
                  #list,
                  [parent, collectionId],
                  {
                    #mask_fieldPaths: mask_fieldPaths,
                    #orderBy: orderBy,
                    #pageSize: pageSize,
                    #pageToken: pageToken,
                    #readTime: readTime,
                    #showMissing: showMissing,
                    #transaction: transaction,
                    #$fields: $fields,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.ListDocumentsResponse>);

  @override
  _i4.Future<_i2.ListCollectionIdsResponse> listCollectionIds(
    _i2.ListCollectionIdsRequest? request,
    String? parent, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listCollectionIds,
              [request, parent],
              {#$fields: $fields},
            ),
            returnValue: _i4.Future<_i2.ListCollectionIdsResponse>.value(
              _FakeListCollectionIdsResponse_16(
                this,
                Invocation.method(
                  #listCollectionIds,
                  [request, parent],
                  {#$fields: $fields},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.ListCollectionIdsResponse>);

  @override
  _i4.Future<_i2.ListDocumentsResponse> listDocuments(
    String? parent,
    String? collectionId, {
    List<String>? mask_fieldPaths,
    String? orderBy,
    int? pageSize,
    String? pageToken,
    String? readTime,
    bool? showMissing,
    String? transaction,
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listDocuments,
              [parent, collectionId],
              {
                #mask_fieldPaths: mask_fieldPaths,
                #orderBy: orderBy,
                #pageSize: pageSize,
                #pageToken: pageToken,
                #readTime: readTime,
                #showMissing: showMissing,
                #transaction: transaction,
                #$fields: $fields,
              },
            ),
            returnValue: _i4.Future<_i2.ListDocumentsResponse>.value(
              _FakeListDocumentsResponse_15(
                this,
                Invocation.method(
                  #listDocuments,
                  [parent, collectionId],
                  {
                    #mask_fieldPaths: mask_fieldPaths,
                    #orderBy: orderBy,
                    #pageSize: pageSize,
                    #pageToken: pageToken,
                    #readTime: readTime,
                    #showMissing: showMissing,
                    #transaction: transaction,
                    #$fields: $fields,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.ListDocumentsResponse>);

  @override
  _i4.Future<_i2.PartitionQueryResponse> partitionQuery(
    _i2.PartitionQueryRequest? request,
    String? parent, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #partitionQuery,
              [request, parent],
              {#$fields: $fields},
            ),
            returnValue: _i4.Future<_i2.PartitionQueryResponse>.value(
              _FakePartitionQueryResponse_17(
                this,
                Invocation.method(
                  #partitionQuery,
                  [request, parent],
                  {#$fields: $fields},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.PartitionQueryResponse>);

  @override
  _i4.Future<_i2.Document> patch(
    _i2.Document? request,
    String? name, {
    bool? currentDocument_exists,
    String? currentDocument_updateTime,
    List<String>? mask_fieldPaths,
    List<String>? updateMask_fieldPaths,
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [request, name],
              {
                #currentDocument_exists: currentDocument_exists,
                #currentDocument_updateTime: currentDocument_updateTime,
                #mask_fieldPaths: mask_fieldPaths,
                #updateMask_fieldPaths: updateMask_fieldPaths,
                #$fields: $fields,
              },
            ),
            returnValue: _i4.Future<_i2.Document>.value(
              _FakeDocument_13(
                this,
                Invocation.method(
                  #patch,
                  [request, name],
                  {
                    #currentDocument_exists: currentDocument_exists,
                    #currentDocument_updateTime: currentDocument_updateTime,
                    #mask_fieldPaths: mask_fieldPaths,
                    #updateMask_fieldPaths: updateMask_fieldPaths,
                    #$fields: $fields,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Document>);

  @override
  _i4.Future<_i3.$Empty> rollback(
    _i2.RollbackRequest? request,
    String? database, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #rollback,
              [request, database],
              {#$fields: $fields},
            ),
            returnValue: _i4.Future<_i3.$Empty>.value(
              _Fake$Empty_14(
                this,
                Invocation.method(
                  #rollback,
                  [request, database],
                  {#$fields: $fields},
                ),
              ),
            ),
          )
          as _i4.Future<_i3.$Empty>);

  @override
  _i4.Future<List<_i2.RunAggregationQueryResponseElement>> runAggregationQuery(
    _i2.RunAggregationQueryRequest? request,
    String? parent, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runAggregationQuery,
              [request, parent],
              {#$fields: $fields},
            ),
            returnValue:
                _i4.Future<List<_i2.RunAggregationQueryResponseElement>>.value(
                  <_i2.RunAggregationQueryResponseElement>[],
                ),
          )
          as _i4.Future<List<_i2.RunAggregationQueryResponseElement>>);

  @override
  _i4.Future<List<_i2.RunQueryResponseElement>> runQuery(
    _i2.RunQueryRequest? request,
    String? parent, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runQuery,
              [request, parent],
              {#$fields: $fields},
            ),
            returnValue: _i4.Future<List<_i2.RunQueryResponseElement>>.value(
              <_i2.RunQueryResponseElement>[],
            ),
          )
          as _i4.Future<List<_i2.RunQueryResponseElement>>);

  @override
  _i4.Future<_i2.WriteResponse> write(
    _i2.WriteRequest? request,
    String? database, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#write, [request, database], {#$fields: $fields}),
            returnValue: _i4.Future<_i2.WriteResponse>.value(
              _FakeWriteResponse_18(
                this,
                Invocation.method(
                  #write,
                  [request, database],
                  {#$fields: $fields},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.WriteResponse>);
}
