// Mocks generated by Mockito 5.4.5 from annotations
// in cocoon_server/test/secret_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:googleapis/secretmanager/v1.dart' as _i2;
import 'package:googleapis/shared.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProjectsResource_0 extends _i1.SmartFake
    implements _i2.ProjectsResource {
  _FakeProjectsResource_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProjectsLocationsResource_1 extends _i1.SmartFake
    implements _i2.ProjectsLocationsResource {
  _FakeProjectsLocationsResource_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProjectsSecretsResource_2 extends _i1.SmartFake
    implements _i2.ProjectsSecretsResource {
  _FakeProjectsSecretsResource_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProjectsSecretsVersionsResource_3 extends _i1.SmartFake
    implements _i2.ProjectsSecretsVersionsResource {
  _FakeProjectsSecretsVersionsResource_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeSecretVersion_4 extends _i1.SmartFake implements _i2.SecretVersion {
  _FakeSecretVersion_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSecret_5 extends _i1.SmartFake implements _i2.Secret {
  _FakeSecret_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$Empty_6 extends _i1.SmartFake implements _i3.$Empty {
  _Fake$Empty_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePolicy_7 extends _i1.SmartFake implements _i2.Policy {
  _FakePolicy_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeListSecretsResponse_8 extends _i1.SmartFake
    implements _i2.ListSecretsResponse {
  _FakeListSecretsResponse_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$PermissionsResponse_9 extends _i1.SmartFake
    implements _i3.$PermissionsResponse {
  _Fake$PermissionsResponse_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAccessSecretVersionResponse_10 extends _i1.SmartFake
    implements _i2.AccessSecretVersionResponse {
  _FakeAccessSecretVersionResponse_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeListSecretVersionsResponse_11 extends _i1.SmartFake
    implements _i2.ListSecretVersionsResponse {
  _FakeListSecretVersionsResponse_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AccessSecretVersionResponse].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccessSecretVersionResponse extends _i1.Mock
    implements _i2.AccessSecretVersionResponse {
  @override
  set name(String? _name) => super.noSuchMethod(
    Invocation.setter(#name, _name),
    returnValueForMissingStub: null,
  );

  @override
  set payload(_i2.SecretPayload? _payload) => super.noSuchMethod(
    Invocation.setter(#payload, _payload),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [SecretPayload].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecretPayload extends _i1.Mock implements _i2.SecretPayload {
  @override
  set data(String? _data) => super.noSuchMethod(
    Invocation.setter(#data, _data),
    returnValueForMissingStub: null,
  );

  @override
  set dataCrc32c(String? _dataCrc32c) => super.noSuchMethod(
    Invocation.setter(#dataCrc32c, _dataCrc32c),
    returnValueForMissingStub: null,
  );

  @override
  List<int> get dataAsBytes =>
      (super.noSuchMethod(
            Invocation.getter(#dataAsBytes),
            returnValue: <int>[],
            returnValueForMissingStub: <int>[],
          )
          as List<int>);

  @override
  set dataAsBytes(List<int>? bytes_) => super.noSuchMethod(
    Invocation.setter(#dataAsBytes, bytes_),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [SecretManagerApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecretManagerApi extends _i1.Mock implements _i2.SecretManagerApi {
  @override
  _i2.ProjectsResource get projects =>
      (super.noSuchMethod(
            Invocation.getter(#projects),
            returnValue: _FakeProjectsResource_0(
              this,
              Invocation.getter(#projects),
            ),
            returnValueForMissingStub: _FakeProjectsResource_0(
              this,
              Invocation.getter(#projects),
            ),
          )
          as _i2.ProjectsResource);
}

/// A class which mocks [ProjectsResource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProjectsResource extends _i1.Mock implements _i2.ProjectsResource {
  @override
  _i2.ProjectsLocationsResource get locations =>
      (super.noSuchMethod(
            Invocation.getter(#locations),
            returnValue: _FakeProjectsLocationsResource_1(
              this,
              Invocation.getter(#locations),
            ),
            returnValueForMissingStub: _FakeProjectsLocationsResource_1(
              this,
              Invocation.getter(#locations),
            ),
          )
          as _i2.ProjectsLocationsResource);

  @override
  _i2.ProjectsSecretsResource get secrets =>
      (super.noSuchMethod(
            Invocation.getter(#secrets),
            returnValue: _FakeProjectsSecretsResource_2(
              this,
              Invocation.getter(#secrets),
            ),
            returnValueForMissingStub: _FakeProjectsSecretsResource_2(
              this,
              Invocation.getter(#secrets),
            ),
          )
          as _i2.ProjectsSecretsResource);
}

/// A class which mocks [ProjectsSecretsResource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProjectsSecretsResource extends _i1.Mock
    implements _i2.ProjectsSecretsResource {
  @override
  _i2.ProjectsSecretsVersionsResource get versions =>
      (super.noSuchMethod(
            Invocation.getter(#versions),
            returnValue: _FakeProjectsSecretsVersionsResource_3(
              this,
              Invocation.getter(#versions),
            ),
            returnValueForMissingStub: _FakeProjectsSecretsVersionsResource_3(
              this,
              Invocation.getter(#versions),
            ),
          )
          as _i2.ProjectsSecretsVersionsResource);

  @override
  _i4.Future<_i2.SecretVersion> addVersion(
    _i2.AddSecretVersionRequest? request,
    String? parent, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addVersion,
              [request, parent],
              {#$fields: $fields},
            ),
            returnValue: _i4.Future<_i2.SecretVersion>.value(
              _FakeSecretVersion_4(
                this,
                Invocation.method(
                  #addVersion,
                  [request, parent],
                  {#$fields: $fields},
                ),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.SecretVersion>.value(
              _FakeSecretVersion_4(
                this,
                Invocation.method(
                  #addVersion,
                  [request, parent],
                  {#$fields: $fields},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.SecretVersion>);

  @override
  _i4.Future<_i2.Secret> create(
    _i2.Secret? request,
    String? parent, {
    String? secretId,
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #create,
              [request, parent],
              {#secretId: secretId, #$fields: $fields},
            ),
            returnValue: _i4.Future<_i2.Secret>.value(
              _FakeSecret_5(
                this,
                Invocation.method(
                  #create,
                  [request, parent],
                  {#secretId: secretId, #$fields: $fields},
                ),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Secret>.value(
              _FakeSecret_5(
                this,
                Invocation.method(
                  #create,
                  [request, parent],
                  {#secretId: secretId, #$fields: $fields},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Secret>);

  @override
  _i4.Future<_i3.$Empty> delete(
    String? name, {
    String? etag,
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [name],
              {#etag: etag, #$fields: $fields},
            ),
            returnValue: _i4.Future<_i3.$Empty>.value(
              _Fake$Empty_6(
                this,
                Invocation.method(
                  #delete,
                  [name],
                  {#etag: etag, #$fields: $fields},
                ),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i3.$Empty>.value(
              _Fake$Empty_6(
                this,
                Invocation.method(
                  #delete,
                  [name],
                  {#etag: etag, #$fields: $fields},
                ),
              ),
            ),
          )
          as _i4.Future<_i3.$Empty>);

  @override
  _i4.Future<_i2.Secret> get(String? name, {String? $fields}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [name], {#$fields: $fields}),
            returnValue: _i4.Future<_i2.Secret>.value(
              _FakeSecret_5(
                this,
                Invocation.method(#get, [name], {#$fields: $fields}),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Secret>.value(
              _FakeSecret_5(
                this,
                Invocation.method(#get, [name], {#$fields: $fields}),
              ),
            ),
          )
          as _i4.Future<_i2.Secret>);

  @override
  _i4.Future<_i2.Policy> getIamPolicy(
    String? resource, {
    int? options_requestedPolicyVersion,
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getIamPolicy,
              [resource],
              {
                #options_requestedPolicyVersion: options_requestedPolicyVersion,
                #$fields: $fields,
              },
            ),
            returnValue: _i4.Future<_i2.Policy>.value(
              _FakePolicy_7(
                this,
                Invocation.method(
                  #getIamPolicy,
                  [resource],
                  {
                    #options_requestedPolicyVersion:
                        options_requestedPolicyVersion,
                    #$fields: $fields,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Policy>.value(
              _FakePolicy_7(
                this,
                Invocation.method(
                  #getIamPolicy,
                  [resource],
                  {
                    #options_requestedPolicyVersion:
                        options_requestedPolicyVersion,
                    #$fields: $fields,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Policy>);

  @override
  _i4.Future<_i2.ListSecretsResponse> list(
    String? parent, {
    String? filter,
    int? pageSize,
    String? pageToken,
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #list,
              [parent],
              {
                #filter: filter,
                #pageSize: pageSize,
                #pageToken: pageToken,
                #$fields: $fields,
              },
            ),
            returnValue: _i4.Future<_i2.ListSecretsResponse>.value(
              _FakeListSecretsResponse_8(
                this,
                Invocation.method(
                  #list,
                  [parent],
                  {
                    #filter: filter,
                    #pageSize: pageSize,
                    #pageToken: pageToken,
                    #$fields: $fields,
                  },
                ),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.ListSecretsResponse>.value(
                  _FakeListSecretsResponse_8(
                    this,
                    Invocation.method(
                      #list,
                      [parent],
                      {
                        #filter: filter,
                        #pageSize: pageSize,
                        #pageToken: pageToken,
                        #$fields: $fields,
                      },
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.ListSecretsResponse>);

  @override
  _i4.Future<_i2.Secret> patch(
    _i2.Secret? request,
    String? name, {
    String? updateMask,
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [request, name],
              {#updateMask: updateMask, #$fields: $fields},
            ),
            returnValue: _i4.Future<_i2.Secret>.value(
              _FakeSecret_5(
                this,
                Invocation.method(
                  #patch,
                  [request, name],
                  {#updateMask: updateMask, #$fields: $fields},
                ),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Secret>.value(
              _FakeSecret_5(
                this,
                Invocation.method(
                  #patch,
                  [request, name],
                  {#updateMask: updateMask, #$fields: $fields},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Secret>);

  @override
  _i4.Future<_i2.Policy> setIamPolicy(
    _i2.SetIamPolicyRequest? request,
    String? resource, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setIamPolicy,
              [request, resource],
              {#$fields: $fields},
            ),
            returnValue: _i4.Future<_i2.Policy>.value(
              _FakePolicy_7(
                this,
                Invocation.method(
                  #setIamPolicy,
                  [request, resource],
                  {#$fields: $fields},
                ),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Policy>.value(
              _FakePolicy_7(
                this,
                Invocation.method(
                  #setIamPolicy,
                  [request, resource],
                  {#$fields: $fields},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Policy>);

  @override
  _i4.Future<_i3.$PermissionsResponse> testIamPermissions(
    _i3.$TestIamPermissionsRequest00? request,
    String? resource, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #testIamPermissions,
              [request, resource],
              {#$fields: $fields},
            ),
            returnValue: _i4.Future<_i3.$PermissionsResponse>.value(
              _Fake$PermissionsResponse_9(
                this,
                Invocation.method(
                  #testIamPermissions,
                  [request, resource],
                  {#$fields: $fields},
                ),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i3.$PermissionsResponse>.value(
                  _Fake$PermissionsResponse_9(
                    this,
                    Invocation.method(
                      #testIamPermissions,
                      [request, resource],
                      {#$fields: $fields},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i3.$PermissionsResponse>);
}

/// A class which mocks [ProjectsSecretsVersionsResource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProjectsSecretsVersionsResource extends _i1.Mock
    implements _i2.ProjectsSecretsVersionsResource {
  @override
  _i4.Future<_i2.AccessSecretVersionResponse> access(
    String? name, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#access, [name], {#$fields: $fields}),
            returnValue: _i4.Future<_i2.AccessSecretVersionResponse>.value(
              _FakeAccessSecretVersionResponse_10(
                this,
                Invocation.method(#access, [name], {#$fields: $fields}),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.AccessSecretVersionResponse>.value(
                  _FakeAccessSecretVersionResponse_10(
                    this,
                    Invocation.method(#access, [name], {#$fields: $fields}),
                  ),
                ),
          )
          as _i4.Future<_i2.AccessSecretVersionResponse>);

  @override
  _i4.Future<_i2.SecretVersion> destroy(
    _i3.$SecretVersionRequest? request,
    String? name, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#destroy, [request, name], {#$fields: $fields}),
            returnValue: _i4.Future<_i2.SecretVersion>.value(
              _FakeSecretVersion_4(
                this,
                Invocation.method(
                  #destroy,
                  [request, name],
                  {#$fields: $fields},
                ),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.SecretVersion>.value(
              _FakeSecretVersion_4(
                this,
                Invocation.method(
                  #destroy,
                  [request, name],
                  {#$fields: $fields},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.SecretVersion>);

  @override
  _i4.Future<_i2.SecretVersion> disable(
    _i3.$SecretVersionRequest? request,
    String? name, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#disable, [request, name], {#$fields: $fields}),
            returnValue: _i4.Future<_i2.SecretVersion>.value(
              _FakeSecretVersion_4(
                this,
                Invocation.method(
                  #disable,
                  [request, name],
                  {#$fields: $fields},
                ),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.SecretVersion>.value(
              _FakeSecretVersion_4(
                this,
                Invocation.method(
                  #disable,
                  [request, name],
                  {#$fields: $fields},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.SecretVersion>);

  @override
  _i4.Future<_i2.SecretVersion> enable(
    _i3.$SecretVersionRequest? request,
    String? name, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#enable, [request, name], {#$fields: $fields}),
            returnValue: _i4.Future<_i2.SecretVersion>.value(
              _FakeSecretVersion_4(
                this,
                Invocation.method(
                  #enable,
                  [request, name],
                  {#$fields: $fields},
                ),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.SecretVersion>.value(
              _FakeSecretVersion_4(
                this,
                Invocation.method(
                  #enable,
                  [request, name],
                  {#$fields: $fields},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.SecretVersion>);

  @override
  _i4.Future<_i2.SecretVersion> get(String? name, {String? $fields}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [name], {#$fields: $fields}),
            returnValue: _i4.Future<_i2.SecretVersion>.value(
              _FakeSecretVersion_4(
                this,
                Invocation.method(#get, [name], {#$fields: $fields}),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.SecretVersion>.value(
              _FakeSecretVersion_4(
                this,
                Invocation.method(#get, [name], {#$fields: $fields}),
              ),
            ),
          )
          as _i4.Future<_i2.SecretVersion>);

  @override
  _i4.Future<_i2.ListSecretVersionsResponse> list(
    String? parent, {
    String? filter,
    int? pageSize,
    String? pageToken,
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #list,
              [parent],
              {
                #filter: filter,
                #pageSize: pageSize,
                #pageToken: pageToken,
                #$fields: $fields,
              },
            ),
            returnValue: _i4.Future<_i2.ListSecretVersionsResponse>.value(
              _FakeListSecretVersionsResponse_11(
                this,
                Invocation.method(
                  #list,
                  [parent],
                  {
                    #filter: filter,
                    #pageSize: pageSize,
                    #pageToken: pageToken,
                    #$fields: $fields,
                  },
                ),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.ListSecretVersionsResponse>.value(
                  _FakeListSecretVersionsResponse_11(
                    this,
                    Invocation.method(
                      #list,
                      [parent],
                      {
                        #filter: filter,
                        #pageSize: pageSize,
                        #pageToken: pageToken,
                        #$fields: $fields,
                      },
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.ListSecretVersionsResponse>);
}
