# Copyright 2019 The Flutter Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

runtime: custom
env: flex
service: default

resources:
  memory_gb: 4.0

handlers:
# The Dart server handles all requests. However, this is used to ensure the 
# assets the dart server needs are uploaded to AppEngine.
- url: /v2/(.*\.(html|css|js|ico|svg|png|jpg|map))$
  application_readable: true # So the dart server can read the files
  # If the Dart custom runtime changes and starts using this handler,
  # we want to know. This will have the app only serve HTML and we
  # will know we can remove the Dart handling code. Just swap
  # index.html to \1
  static_files: build/web/index.html
  upload: build/web/.*\.(html|css|js|ico|svg|png|jpg|map)$ # This cannot use the parent directory
