# Copyright 2019 The Flutter Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

runtime: custom
env: flex
service: default

resources:
  memory_gb: 4.0

handlers:
# The Dart server handles all requests. However, this is used to ensure the 
# assets the dart server needs are uploaded to AppEngine.
- url: /v2/(.*\.(html|css|js|ico|svg|png|jpg|map|dart|json))$
  application_readable: true # This is so the dart server can read the files
  static_files: build/web/\1
  upload: build/web/.*\.(html|css|js|ico|svg|png|jpg|map|dart|json)$ # this cannot use the parent directory
  secure: always