targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - always_specify_types
            - implicit_dynamic_parameter
      gql_build|schema_builder:
        enabled: true
      gql_build|ast_builder:
        enabled: true
      gql_build|op_builder:
        enabled: true
        options:
          schema: cocoon_service|lib/src/service/github/schema.public.graphql
      gql_build|data_builder:
        enabled: true
        options:
          schema: cocoon_service|lib/src/service/github/schema.public.graphql
      gql_build|var_builder:
        enabled: true
        options:
          schema: cocoon_service|lib/src/service/github/schema.public.graphql
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: cocoon_service|lib/src/service/github/schema.public.graphql