steps:
  # Build docker image
  - name: 'us-docker.pkg.dev/cloud-builders/ga/v1/docker'
    args: ['build', '-t', 'us-docker.pkg.dev/$PROJECT_ID/appengine/default.version-12345', 'app_dart']

timeout: 1200s

images: ['us-docker.pkg.dev/$PROJECT_ID/appengine/default.version-12345']

# If build provenance is not generated, the docker deployment will fail.
options:
  requestedVerifyOption: VERIFIED
