# Provide instructions for google Cloud Build to build and upload the flutter
# dashboard docker image to artifact registry.

steps:
  # Build dashboard.
  # This step generates the dashboard files using flutter, then moves the
  # generated files into the app_dart folder, where a docker image is then
  # created in the next step.
  - name: us-docker.pkg.dev/$PROJECT_ID/flutter/flutter
    entrypoint: '/bin/bash'
    args: ['cloud_build/dashboard_build.sh']

  # Build docker image
  - name: 'us-docker.pkg.dev/cloud-builders/ga/v1/docker'
    args: ['build', '-t', 'us-docker.pkg.dev/$PROJECT_ID/appengine/default.version-$SHORT_SHA', 'app_dart']

timeout: 1200s

images: ['us-docker.pkg.dev/$PROJECT_ID/appengine/default.version-$SHORT_SHA']

# If build provenance is not generated, the docker deployment will fail.
options:
  requestedVerifyOption: VERIFIED
