# Provide instructions for google Cloud Build to auto-build flutter
# dashboard to flutter-dashboard project. Auto-build will be triggered
# by daily schedule on `main` branch. This cloudbuild calls two cloudbuild
# configurations.
#
# The first job is for generating the docker image with build provenance,
# and the second uses the generated docker image and deploys it to app engine.

steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |-
        ls

timeout: 1200s
