steps:
  # Try to pull the latest image for caching
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker pull us-central1-docker.pkg.dev/flutter-infra/flutter-infra/flutter_docker:latest || exit 0'

  # Do the build
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      # Use the cache, maybe.
      - '--cache-from'
      - 'us-central1-docker.pkg.dev/flutter-infra/flutter-infra/flutter_docker:latest'
      # Pass the Cloud Build substitution into the Dockerfile ARG
      - '--build-arg'
      - 'FLUTTER_VERSION=$_FLUTTER_VERSION'
      # Tag it with the specific version in Artifact Registry
      - '-t'
      - 'us-central1-docker.pkg.dev/flutter-infra/flutter-infra/flutter_docker:$_FLUTTER_VERSION'
      # Also tag it as latest in Artifact Registry
      - '-t'
      - 'us-central1-docker.pkg.dev/flutter-infra/flutter-infra/flutter_docker:latest'
      - '.'

# Define the default version here so manual triggers still work
substitutions:
  _FLUTTER_VERSION: "3.44.2"

images:
  - 'us-central1-docker.pkg.dev/flutter-infra/flutter-infra/flutter_docker:$_FLUTTER_VERSION'
  - 'us-central1-docker.pkg.dev/flutter-infra/flutter-infra/flutter_docker:latest'

options:
  logging: CLOUD_LOGGING_ONLY
