// Copyright 2026 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'dart:io';

import 'package:native_assets_cli/native_assets_cli.dart';

void main(List<String> args) async {
  await build(args, (config, output) async {
    // 1. Read the source file (the code freeze config)
    final configFile = File('lib/configuration/code_freeze.yaml');
    final content = await configFile.readAsString();

    // 2. Define the path for the generated code
    final outputFile = File('lib/src/generated_config.dart');

    // 3. Write the file as a raw string constant
    await outputFile.writeAsString("""
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by hook/build.dart

const String codeFreezeConfigContent =
    r'''$content''';
""");

    // 4. Tell Dart that this hook depends on the config file
    output.addDependency(configFile.uri);
  });
}
