const String commentOnNonPullRequestIssuePayload = '''
{
  "action": "created",
  "issue": {
    "url": "https://api.github.com/repos/ricardoamador/flutter_test/issues/10",
    "repository_url": "https://api.github.com/repos/ricardoamador/flutter_test",
    "labels_url": "https://api.github.com/repos/ricardoamador/flutter_test/issues/10/labels{/name}",
    "comments_url": "https://api.github.com/repos/ricardoamador/flutter_test/issues/10/comments",
    "events_url": "https://api.github.com/repos/ricardoamador/flutter_test/issues/10/events",
    "html_url": "https://github.com/ricardoamador/flutter_test/issues/10",
    "id": 1578819463,
    "node_id": "I_kwDOIRxr_M5eGt-H",
    "number": 10,
    "title": "Test issue to see if these differ from pull requests via github.",
    "user": {
      "login": "ricardoamador",
      "id": 32242716,
      "node_id": "MDQ6VXNlcjMyMjQyNzE2",
      "avatar_url": "https://avatars.githubusercontent.com/u/32242716?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ricardoamador",
      "html_url": "https://github.com/ricardoamador",
      "followers_url": "https://api.github.com/users/ricardoamador/followers",
      "following_url": "https://api.github.com/users/ricardoamador/following{/other_user}",
      "gists_url": "https://api.github.com/users/ricardoamador/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ricardoamador/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ricardoamador/subscriptions",
      "organizations_url": "https://api.github.com/users/ricardoamador/orgs",
      "repos_url": "https://api.github.com/users/ricardoamador/repos",
      "events_url": "https://api.github.com/users/ricardoamador/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ricardoamador/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 1,
    "created_at": "2023-02-10T00:44:37Z",
    "updated_at": "2023-02-10T00:45:07Z",
    "closed_at": null,
    "author_association": "OWNER",
    "active_lock_reason": null,
    "body": null,
    "reactions": {
      "url": "https://api.github.com/repos/ricardoamador/flutter_test/issues/10/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/ricardoamador/flutter_test/issues/10/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  "comment": {
    "url": "https://api.github.com/repos/ricardoamador/flutter_test/issues/comments/1425024464",
    "html_url": "https://github.com/ricardoamador/flutter_test/issues/10#issuecomment-1425024464",
    "issue_url": "https://api.github.com/repos/ricardoamador/flutter_test/issues/10",
    "id": 1425024464,
    "node_id": "IC_kwDOIRxr_M5U8CXQ",
    "user": {
      "login": "ricardoamador",
      "id": 32242716,
      "node_id": "MDQ6VXNlcjMyMjQyNzE2",
      "avatar_url": "https://avatars.githubusercontent.com/u/32242716?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ricardoamador",
      "html_url": "https://github.com/ricardoamador",
      "followers_url": "https://api.github.com/users/ricardoamador/followers",
      "following_url": "https://api.github.com/users/ricardoamador/following{/other_user}",
      "gists_url": "https://api.github.com/users/ricardoamador/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ricardoamador/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ricardoamador/subscriptions",
      "organizations_url": "https://api.github.com/users/ricardoamador/orgs",
      "repos_url": "https://api.github.com/users/ricardoamador/repos",
      "events_url": "https://api.github.com/users/ricardoamador/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ricardoamador/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-02-10T00:45:07Z",
    "updated_at": "2023-02-10T00:45:07Z",
    "author_association": "OWNER",
    "body": "Test comment on a non pull request.",
    "reactions": {
      "url": "https://api.github.com/repos/ricardoamador/flutter_test/issues/comments/1425024464/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  "repository": {
    "id": 555510780,
    "node_id": "R_kgDOIRxr_A",
    "name": "flutter_test",
    "full_name": "ricardoamador/flutter_test",
    "private": true,
    "owner": {
      "login": "ricardoamador",
      "id": 32242716,
      "node_id": "MDQ6VXNlcjMyMjQyNzE2",
      "avatar_url": "https://avatars.githubusercontent.com/u/32242716?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ricardoamador",
      "html_url": "https://github.com/ricardoamador",
      "followers_url": "https://api.github.com/users/ricardoamador/followers",
      "following_url": "https://api.github.com/users/ricardoamador/following{/other_user}",
      "gists_url": "https://api.github.com/users/ricardoamador/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ricardoamador/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ricardoamador/subscriptions",
      "organizations_url": "https://api.github.com/users/ricardoamador/orgs",
      "repos_url": "https://api.github.com/users/ricardoamador/repos",
      "events_url": "https://api.github.com/users/ricardoamador/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ricardoamador/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/ricardoamador/flutter_test",
    "description": "Test repository for checking git commands",
    "fork": false,
    "url": "https://api.github.com/repos/ricardoamador/flutter_test",
    "forks_url": "https://api.github.com/repos/ricardoamador/flutter_test/forks",
    "keys_url": "https://api.github.com/repos/ricardoamador/flutter_test/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/ricardoamador/flutter_test/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/ricardoamador/flutter_test/teams",
    "hooks_url": "https://api.github.com/repos/ricardoamador/flutter_test/hooks",
    "issue_events_url": "https://api.github.com/repos/ricardoamador/flutter_test/issues/events{/number}",
    "events_url": "https://api.github.com/repos/ricardoamador/flutter_test/events",
    "assignees_url": "https://api.github.com/repos/ricardoamador/flutter_test/assignees{/user}",
    "branches_url": "https://api.github.com/repos/ricardoamador/flutter_test/branches{/branch}",
    "tags_url": "https://api.github.com/repos/ricardoamador/flutter_test/tags",
    "blobs_url": "https://api.github.com/repos/ricardoamador/flutter_test/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/ricardoamador/flutter_test/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/ricardoamador/flutter_test/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/ricardoamador/flutter_test/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/ricardoamador/flutter_test/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/ricardoamador/flutter_test/languages",
    "stargazers_url": "https://api.github.com/repos/ricardoamador/flutter_test/stargazers",
    "contributors_url": "https://api.github.com/repos/ricardoamador/flutter_test/contributors",
    "subscribers_url": "https://api.github.com/repos/ricardoamador/flutter_test/subscribers",
    "subscription_url": "https://api.github.com/repos/ricardoamador/flutter_test/subscription",
    "commits_url": "https://api.github.com/repos/ricardoamador/flutter_test/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/ricardoamador/flutter_test/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/ricardoamador/flutter_test/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/ricardoamador/flutter_test/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/ricardoamador/flutter_test/contents/{+path}",
    "compare_url": "https://api.github.com/repos/ricardoamador/flutter_test/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/ricardoamador/flutter_test/merges",
    "archive_url": "https://api.github.com/repos/ricardoamador/flutter_test/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/ricardoamador/flutter_test/downloads",
    "issues_url": "https://api.github.com/repos/ricardoamador/flutter_test/issues{/number}",
    "pulls_url": "https://api.github.com/repos/ricardoamador/flutter_test/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/ricardoamador/flutter_test/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/ricardoamador/flutter_test/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/ricardoamador/flutter_test/labels{/name}",
    "releases_url": "https://api.github.com/repos/ricardoamador/flutter_test/releases{/id}",
    "deployments_url": "https://api.github.com/repos/ricardoamador/flutter_test/deployments",
    "created_at": "2022-10-21T18:20:42Z",
    "updated_at": "2022-10-21T18:22:20Z",
    "pushed_at": "2022-12-14T22:44:11Z",
    "git_url": "git://github.com/ricardoamador/flutter_test.git",
    "ssh_url": "git@github.com:ricardoamador/flutter_test.git",
    "clone_url": "https://github.com/ricardoamador/flutter_test.git",
    "svn_url": "https://github.com/ricardoamador/flutter_test",
    "homepage": null,
    "size": 276,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "C++",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 2,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [

    ],
    "visibility": "private",
    "forks": 0,
    "open_issues": 2,
    "watchers": 0,
    "default_branch": "main"
  },
  "sender": {
    "login": "ricardoamador",
    "id": 32242716,
    "node_id": "MDQ6VXNlcjMyMjQyNzE2",
    "avatar_url": "https://avatars.githubusercontent.com/u/32242716?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ricardoamador",
    "html_url": "https://github.com/ricardoamador",
    "followers_url": "https://api.github.com/users/ricardoamador/followers",
    "following_url": "https://api.github.com/users/ricardoamador/following{/other_user}",
    "gists_url": "https://api.github.com/users/ricardoamador/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ricardoamador/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ricardoamador/subscriptions",
    "organizations_url": "https://api.github.com/users/ricardoamador/orgs",
    "repos_url": "https://api.github.com/users/ricardoamador/repos",
    "events_url": "https://api.github.com/users/ricardoamador/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ricardoamador/received_events",
    "type": "User",
    "site_admin": false
  }
}
''';

const String commentOnPullRequestPayload = '''
{
  "action": "created",
  "issue": {
    "url": "https://api.github.com/repos/ricardoamador/flutter_test/issues/9",
    "repository_url": "https://api.github.com/repos/ricardoamador/flutter_test",
    "labels_url": "https://api.github.com/repos/ricardoamador/flutter_test/issues/9/labels{/name}",
    "comments_url": "https://api.github.com/repos/ricardoamador/flutter_test/issues/9/comments",
    "events_url": "https://api.github.com/repos/ricardoamador/flutter_test/issues/9/events",
    "html_url": "https://github.com/ricardoamador/flutter_test/pull/9",
    "id": 1497518469,
    "node_id": "PR_kwDOIRxr_M5Ff1-I",
    "number": 9,
    "title": "Revert Updated readme",
    "user": {
      "login": "revert[bot]",
      "id": 120533631,
      "node_id": "BOT_kgDOBy8yfw",
      "avatar_url": "https://avatars.githubusercontent.com/u/32242716?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/revert%5Bbot%5D",
      "html_url": "https://github.com/apps/revert",
      "followers_url": "https://api.github.com/users/revert%5Bbot%5D/followers",
      "following_url": "https://api.github.com/users/revert%5Bbot%5D/following{/other_user}",
      "gists_url": "https://api.github.com/users/revert%5Bbot%5D/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/revert%5Bbot%5D/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/revert%5Bbot%5D/subscriptions",
      "organizations_url": "https://api.github.com/users/revert%5Bbot%5D/orgs",
      "repos_url": "https://api.github.com/users/revert%5Bbot%5D/repos",
      "events_url": "https://api.github.com/users/revert%5Bbot%5D/events{/privacy}",
      "received_events_url": "https://api.github.com/users/revert%5Bbot%5D/received_events",
      "type": "Bot",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 1,
    "created_at": "2022-12-14T22:44:10Z",
    "updated_at": "2023-02-08T22:43:26Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
      "url": "https://api.github.com/repos/ricardoamador/flutter_test/pulls/9",
      "html_url": "https://github.com/ricardoamador/flutter_test/pull/9",
      "diff_url": "https://github.com/ricardoamador/flutter_test/pull/9.diff",
      "patch_url": "https://github.com/ricardoamador/flutter_test/pull/9.patch",
      "merged_at": null
    },
    "body": null,
    "reactions": {
      "url": "https://api.github.com/repos/ricardoamador/flutter_test/issues/9/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/ricardoamador/flutter_test/issues/9/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  "comment": {
    "url": "https://api.github.com/repos/ricardoamador/flutter_test/issues/comments/1423335532",
    "html_url": "https://github.com/ricardoamador/flutter_test/pull/9#issuecomment-1423335532",
    "issue_url": "https://api.github.com/repos/ricardoamador/flutter_test/issues/9",
    "id": 1423335532,
    "node_id": "IC_kwDOIRxr_M5U1mBs",
    "user": {
      "login": "ricardoamador",
      "id": 32242716,
      "node_id": "MDQ6VXNlcjMyMjQyNzE2",
      "avatar_url": "https://avatars.githubusercontent.com/u/32242716?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ricardoamador",
      "html_url": "https://github.com/ricardoamador",
      "followers_url": "https://api.github.com/users/ricardoamador/followers",
      "following_url": "https://api.github.com/users/ricardoamador/following{/other_user}",
      "gists_url": "https://api.github.com/users/ricardoamador/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ricardoamador/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ricardoamador/subscriptions",
      "organizations_url": "https://api.github.com/users/ricardoamador/orgs",
      "repos_url": "https://api.github.com/users/ricardoamador/repos",
      "events_url": "https://api.github.com/users/ricardoamador/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ricardoamador/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-02-08T22:43:26Z",
    "updated_at": "2023-02-08T22:43:26Z",
    "author_association": "OWNER",
    "body": "Issue comment payload test.",
    "reactions": {
      "url": "https://api.github.com/repos/ricardoamador/flutter_test/issues/comments/1423335532/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  "repository": {
    "id": 555510780,
    "node_id": "R_kgDOIRxr_A",
    "name": "flutter_test",
    "full_name": "ricardoamador/flutter_test",
    "private": true,
    "owner": {
      "login": "ricardoamador",
      "id": 32242716,
      "node_id": "MDQ6VXNlcjMyMjQyNzE2",
      "avatar_url": "https://avatars.githubusercontent.com/u/32242716?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ricardoamador",
      "html_url": "https://github.com/ricardoamador",
      "followers_url": "https://api.github.com/users/ricardoamador/followers",
      "following_url": "https://api.github.com/users/ricardoamador/following{/other_user}",
      "gists_url": "https://api.github.com/users/ricardoamador/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ricardoamador/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ricardoamador/subscriptions",
      "organizations_url": "https://api.github.com/users/ricardoamador/orgs",
      "repos_url": "https://api.github.com/users/ricardoamador/repos",
      "events_url": "https://api.github.com/users/ricardoamador/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ricardoamador/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/ricardoamador/flutter_test",
    "description": "Test repository for checking git commands",
    "fork": false,
    "url": "https://api.github.com/repos/ricardoamador/flutter_test",
    "forks_url": "https://api.github.com/repos/ricardoamador/flutter_test/forks",
    "keys_url": "https://api.github.com/repos/ricardoamador/flutter_test/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/ricardoamador/flutter_test/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/ricardoamador/flutter_test/teams",
    "hooks_url": "https://api.github.com/repos/ricardoamador/flutter_test/hooks",
    "issue_events_url": "https://api.github.com/repos/ricardoamador/flutter_test/issues/events{/number}",
    "events_url": "https://api.github.com/repos/ricardoamador/flutter_test/events",
    "assignees_url": "https://api.github.com/repos/ricardoamador/flutter_test/assignees{/user}",
    "branches_url": "https://api.github.com/repos/ricardoamador/flutter_test/branches{/branch}",
    "tags_url": "https://api.github.com/repos/ricardoamador/flutter_test/tags",
    "blobs_url": "https://api.github.com/repos/ricardoamador/flutter_test/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/ricardoamador/flutter_test/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/ricardoamador/flutter_test/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/ricardoamador/flutter_test/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/ricardoamador/flutter_test/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/ricardoamador/flutter_test/languages",
    "stargazers_url": "https://api.github.com/repos/ricardoamador/flutter_test/stargazers",
    "contributors_url": "https://api.github.com/repos/ricardoamador/flutter_test/contributors",
    "subscribers_url": "https://api.github.com/repos/ricardoamador/flutter_test/subscribers",
    "subscription_url": "https://api.github.com/repos/ricardoamador/flutter_test/subscription",
    "commits_url": "https://api.github.com/repos/ricardoamador/flutter_test/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/ricardoamador/flutter_test/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/ricardoamador/flutter_test/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/ricardoamador/flutter_test/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/ricardoamador/flutter_test/contents/{+path}",
    "compare_url": "https://api.github.com/repos/ricardoamador/flutter_test/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/ricardoamador/flutter_test/merges",
    "archive_url": "https://api.github.com/repos/ricardoamador/flutter_test/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/ricardoamador/flutter_test/downloads",
    "issues_url": "https://api.github.com/repos/ricardoamador/flutter_test/issues{/number}",
    "pulls_url": "https://api.github.com/repos/ricardoamador/flutter_test/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/ricardoamador/flutter_test/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/ricardoamador/flutter_test/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/ricardoamador/flutter_test/labels{/name}",
    "releases_url": "https://api.github.com/repos/ricardoamador/flutter_test/releases{/id}",
    "deployments_url": "https://api.github.com/repos/ricardoamador/flutter_test/deployments",
    "created_at": "2022-10-21T18:20:42Z",
    "updated_at": "2022-10-21T18:22:20Z",
    "pushed_at": "2022-12-14T22:44:11Z",
    "git_url": "git://github.com/ricardoamador/flutter_test.git",
    "ssh_url": "git@github.com:ricardoamador/flutter_test.git",
    "clone_url": "https://github.com/ricardoamador/flutter_test.git",
    "svn_url": "https://github.com/ricardoamador/flutter_test",
    "homepage": null,
    "size": 276,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "C++",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 1,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [

    ],
    "visibility": "private",
    "forks": 0,
    "open_issues": 1,
    "watchers": 0,
    "default_branch": "main"
  },
  "sender": {
    "login": "ricardoamador",
    "id": 32242716,
    "node_id": "MDQ6VXNlcjMyMjQyNzE2",
    "avatar_url": "https://avatars.githubusercontent.com/u/32242716?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ricardoamador",
    "html_url": "https://github.com/ricardoamador",
    "followers_url": "https://api.github.com/users/ricardoamador/followers",
    "following_url": "https://api.github.com/users/ricardoamador/following{/other_user}",
    "gists_url": "https://api.github.com/users/ricardoamador/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ricardoamador/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ricardoamador/subscriptions",
    "organizations_url": "https://api.github.com/users/ricardoamador/orgs",
    "repos_url": "https://api.github.com/users/ricardoamador/repos",
    "events_url": "https://api.github.com/users/ricardoamador/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ricardoamador/received_events",
    "type": "User",
    "site_admin": false
  }
}
''';

const String nonCreateCommentPayload = '''
{
  "action": "edited",
  "issue": {
    "id": 1497518469,
    "node_id": "PR_kwDOIRxr_M5Ff1-I",
    "number": 9,
    "title": "Revert Updated readme",
    "user": {
      "login": "revert[bot]",
      "id": 120533631,
      "node_id": "BOT_kgDOBy8yfw"
    },
    "state": "open",
    "locked": false
  },
  "comment": {
    "id": 1423335532,
    "node_id": "IC_kwDOIRxr_M5U1mBs",
    "created_at": "2023-02-08T22:43:26Z",
    "updated_at": "2023-02-08T22:43:26Z",
    "author_association": "OWNER",
    "body": "Issue comment payload test."
  },
  "repository": {
    "id": 555510780,
    "node_id": "R_kgDOIRxr_A",
    "name": "flutter_test",
    "full_name": "ricardoamador/flutter_test",
    "private": true,
    "owner": {
      "login": "ricardoamador",
      "id": 32242716
    }
  },
  "sender": {
    "login": "ricardoamador",
    "id": 32242716,
    "node_id": "MDQ6VXNlcjMyMjQyNzE2"
  }
}
''';

const String partialPayload = '''
{
  "action": "created",
  "issue": {
    "url": "https://api.github.com/repos/ricardoamador/flutter_test/issues/9",
    "repository_url": "https://api.github.com/repos/ricardoamador/flutter_test",
    "html_url": "https://github.com/ricardoamador/flutter_test/pull/9",
    "id": 1497518469,
    "node_id": "PR_kwDOIRxr_M5Ff1-I",
    "number": 9,
    "title": "Revert Updated readme",
    "user": {
      "login": "revert[bot]",
      "id": 120533631,
      "node_id": "BOT_kgDOBy8yfw",
      "avatar_url": "https://avatars.githubusercontent.com/u/32242716?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/revert%5Bbot%5D",
      "html_url": "https://github.com/apps/revert",
      "type": "Bot",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 1,
    "created_at": "2022-12-14T22:44:10Z",
    "updated_at": "2023-02-08T22:43:26Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
      "url": "https://api.github.com/repos/ricardoamador/flutter_test/pulls/9",
      "html_url": "https://github.com/ricardoamador/flutter_test/pull/9",
      "diff_url": "https://github.com/ricardoamador/flutter_test/pull/9.diff",
      "patch_url": "https://github.com/ricardoamador/flutter_test/pull/9.patch",
      "merged_at": null
    },
    "body": null,
    "reactions": {
      "url": "https://api.github.com/repos/ricardoamador/flutter_test/issues/9/reactions"
    },
    "timeline_url": "https://api.github.com/repos/ricardoamador/flutter_test/issues/9/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  "comment": {
    "url": "https://api.github.com/repos/ricardoamador/flutter_test/issues/comments/1423335532",
    "html_url": "https://github.com/ricardoamador/flutter_test/pull/9#issuecomment-1423335532",
    "issue_url": "https://api.github.com/repos/ricardoamador/flutter_test/issues/9",
    "id": 1423335532,
    "node_id": "IC_kwDOIRxr_M5U1mBs",
    "user": {
      "login": "ricardoamador",
      "id": 32242716,
      "node_id": "MDQ6VXNlcjMyMjQyNzE2",
      "avatar_url": "https://avatars.githubusercontent.com/u/32242716?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ricardoamador",
      "html_url": "https://github.com/ricardoamador",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-02-08T22:43:26Z",
    "updated_at": "2023-02-08T22:43:26Z",
    "author_association": "OWNER",
    "body": "Issue comment payload test.",
    "reactions": {
      "url": "https://api.github.com/repos/ricardoamador/flutter_test/issues/comments/1423335532/reactions",
      "total_count": 0
    },
    "performed_via_github_app": null
  }
}
''';

const String gitReference = '''
{
  "ref": "refs/heads/main",
  "node_id": "MDM6UmVmNjMyNjA1NTQ6cmVmcy9oZWFkcy9tYWlu",
  "url": "https://api.github.com/repos/flutter/cocoon/git/refs/heads/main",
  "object": {
    "sha": "6c49dbe90ff3e73b2989619b7760b644c1ed96fe",
    "type": "commit",
    "url": "https://api.github.com/repos/flutter/cocoon/git/commits/6c49dbe90ff3e73b2989619b7760b644c1ed96fe"
  }
}
''';
