name: gcs_cleaner
description: CLI tool for removing engine artifacts from GCS that are not used
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.0

dependencies:
  args: ^2.4.2
  file: ^6.1.4
  gcloud: ^0.8.11
  googleapis_auth: ^1.4.1
  logging: ^1.2.0
  meta: ^1.11.0
  process: ^4.2.4

dev_dependencies:
  flutter_lints: ^2.0.3
  lints: ^2.0.0
  test: ^1.21.0
