// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by hook/build.dart

const String codeFreezeConfigContent =
    r'''flutter/flutter:
  frozen_labels:
    - "f: material design"
    - "f: cupertino"
  frozen_paths:
    - "packages/flutter/lib/src/material/"
    - "packages/flutter/lib/src/cupertino/"
''';
