// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by build.dart hook

const String configFileContent =
    r'''# Defines the config options for Flutter CI (Cocoon)
#
# The schema for this file is defined in DynamicConfig of
# app_dart/lib/src/service/config.dart

# TODO(matanlurey): Remove this flag, it is currently unused.
allowManualTreeClosures: true

backfillerCommitLimit: 50

ciYaml:

contentAwareHashing:
  # This will cause PRs that enter the merge queue to wait on CAH hashing
  # to happen before scheduling builds.
  waitOnContentHash: true

# Whether to close the MQ guard right after LUCI presubmit completed
# instead of doing that as part of the `check_run` GitHub event handling.
closeMqGuardAfterPresubmit: true

# Whether to allow the tree status to be suppressed for specific failed tests.
dynamicTestSuppression: true

# Whether to allow unified check run flow to specific users or to everyone.
unifiedCheckRunFlow:
  useForAll: false
  useForUsers:
    - ievdokdm
    - matanlurey
''';
