name: cocoon_common
description: Shared functionality and interfaces across flutter/cocoon
publish_to: none

environment:
  sdk: ^3.7.0

resolution: workspace

dependencies:
  collection: ^1.19.1
  json_annotation: ^4.9.0
  meta: ^1.16.0
  stack_trace: ^1.12.1

dev_dependencies:
  build_runner: ^2.4.15
  cocoon_common_test:
    path: ../cocoon_common_test
  dart_flutter_team_lints:
  json_serializable: ^6.9.4
  test: ^1.25.15
