name: no-response-publish

# Declare default permissions as read only.
permissions: read-all

on:
  release:
    types: [published, edited]
    branches:
      - main
    paths:
      - 'gh_actions/third_party/no-response/**'
      - '.github/workflows/no-response_test.yaml'
      - '.github/workflows/no-response_publish.yaml'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ github.repository == 'flutter/cocoon' }}
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
        with:
          ref: ${{ github.event.release.tag_name }}
          sparse-checkout: 'gh_actions/third_party/no-response'
          sparse-checkout-cone-mode: false
      - name: move_package_to_root
        run: |
          mv -f gh_actions/third_party/no-response/{.[!.],}* ./
          rm -rf gh_actions
      - name: ls
        run: ls -la
      - name: npm_ci
        run: npm ci
      - name: npm_run_build
        run: npm run build
      - uses: JasonEtco/build-and-tag-action@dd5e4991048c325f6d85b4155e586fc211c644da
        env:
          GITHUB_TOKEN: ${{ secrets.FLUTTERGITHUBBOT_TOKEN }}
