name: no-response-publish

on:
  release:
    types: [published, edited]
    branches:
      - main
    paths:
      - ./gh_actions/third_party/no-response/**

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'flutter/cocoon' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: npm_ci
        working-directory: ./gh_actions/third_party/no-response
        run: npm ci
      - name: npm_run_build
        working-directory: ./gh_actions/third_party/no-response
        run: npm run build
      - uses: JasonEtco/build-and-tag-action@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        working-directory: ./gh_actions/third_party/no-response
