name: no-response-publish

# Declare default permissions as read only.
permissions: read-all

on:
  release:
    types: [published, edited]
    branches:
      - main
    paths:
      - 'gh_actions/third_party/no-response/**'

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'flutter/cocoon' }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          ref: ${{ github.event.release.tag_name }}
          sparse-checkout: 'gh_actions/third_party/no-response'
          sparse-checkout-cone-mode: false
      - name: npm_ci
        run: npm ci
      - name: npm_run_build
        run: npm run build
      - uses: JasonEtco/build-and-tag-action@dd5e4991048c325f6d85b4155e586fc211c644da
        env:
          GITHUB_TOKEN: ${{ github.token }}
